### ISSUE TITLE
Write tests for the gemPath and requires options

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-gradle-plugin#104]
Write tests to verify that the gemPath and requires options are passed to AsciidoctorJ propertly (and that our hack to access the proxy delegate works).

The way to verify this behavior is to evaluate a Ruby scriptlet to access it's `ENV['GEM_PATH']` value and check that a built-in library not loaded by default can be loaded (a good example is 'digest/md5' and verify that `::Digest::MD5` exists or something).

**Comment by ysb33r** [comment]
I've already done `requires` tests for 2.0. Will add some gemPath tests as well.
