### ISSUE TITLE
"toc" attribute in document overridden by plugin configuration

### ISSUE THREAD

**Issue by gernotstarke** [asciidoctor/asciidoctor-gradle-plugin#119]
I convert two documents - one needs a :toc:, the other not.
When I leave the attribute-setting out of the build.gradle, no toc is ever rendered.
When I include the attribute-setting in build.gradle, the toc is rendered for both docs.

btw - I'm using v 1.5.0 of the plugin

placement-setting works... 

I tried placing the :toc!: setting prior to the =heading... no effect

Both docs contain explicit settings for their toc:

doc-1: (DevGuide.adoc)
```asciidoc
    = Development Guide
    :toc:
    :toclevels: 2
    :toc-position: right
    :experimental:
```

doc-2: (index.adoc)
```asciidoc
    = Documentation Overview
    :toc!:
```

build.gradle  (excerpt)
```asciidoc
 asciidoctor {
     outputDir = new File(outputPath)
     sourceDir = file( asciidocSrcPath )
     sourceDocumentNames = files(  
                                   new File( devguide),
                                   new File( index) )
           options = [
            attributes: [
                backend     : 'html5',
                toc         : 'left',
```

**Comment by aalmiray** [comment]
*bump*

**Comment by mojavelinux** [comment]
> @mojavelinux should be automatically add a trailing @ or is this best left as an explicit setting that the developer must make?

This is something the build author should specify. The plugin should not modify the value. If the build author does not put `@` at the end of the value, then that's an intent to override whatever is specified in the document.

The `@` is documented in the user manual (http://asciidoctor.org/docs/user-manual/#attribute-assignment-precedence) and man page, though we likely want to include it in the README for the plugin as a reminder.
