### ISSUE TITLE
Unknown backend PDF

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#141]
When using `asciidoctor-pdf` with the plugin, the message`Passing through unknown backend: pdf` is printed. Now that `pdf` is an official backend, we need to update the plugin to no longer print this warning.

_IMPLEMENTATIOn NOTE_: Probably just needs an update to `AsciidoctorBackend.groovy`.

**Comment by kastork** [comment]
Warning or no, how do you get it to use the backend at all?

```
asciidoctorj {
  version = '1.5.2'
}
asciidoctor {
  backends : ['pdf']
}
```
doesn't do it.  Neither does
```
asciidoctorj {
  version = '1.5.2'
}
asciidoctor {
  backends : [pdf]
}
```


 Is there more config needed?

**Comment by aalmiray** [comment]
@kastork: you must add `asciidoctorj-pdf` as a script dependency

    buildscript {
        repositories {
            jcenter()
        }

        dependencies {
            classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.2'
            classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.6'
        }
    }

**Comment by kastork** [comment]
@aalmiray Thanks!

Sweet project, by the way... all of it

**Comment by mojavelinux** [comment]
:+1:
