### ISSUE TITLE
Setup build on AppVeyor to test on Windows

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-gradle-plugin#144]
Setup a build on AppVeyor so the continuous integration build is run on Windows to complement the Travis CI build on Linux.

You can see a similar configurations here:

* https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/appveyor.yml
* https://github.com/asciidoctor/asciidoctorj/blob/master/appveyor.yml

I've created a stub for the build on the Asciidoctor account on AppVeyor.

https://ci.appveyor.com/project/asciidoctor/asciidoctor-gradle-plugin

I'll forward the credentials to @aalmiray and @ysb33r.

**Comment by aalmiray** [comment]
Looks like it's up and running.

**Comment by mojavelinux** [comment]
Indeed. I think we can close.
