### ISSUE TITLE
hightlight.js version?

### ISSUE THREAD

**Issue by danhyun** [asciidoctor/asciidoctor-gradle-plugin#149]
So according to this https://github.com/asciidoctor/asciidoctor/blob/f86e65d92bf0af5e05d30d1983b57daa57286b51/lib/asciidoctor/converter/html5.rb#L100 hightlight.js should be resolving to 8.4 but when I generate html it's going to version 7.4

> http://cdnjs.cloudflare.com/ajax/libs/highlight.js/7.4/styles/idea.min.css

This is based from this project https://github.com/danhyun/git-2015-session

This is with asciidoctor 1.5.2 https://github.com/danhyun/git-2015-session/blob/master/build.gradle#L7

**Comment by mojavelinux** [comment]
The highlight.js link is controlled by the backend. While it's true that the HTML5 backend embeds 8.4, the reveal.js backend is lagging behind. Here's the line that needs updating:

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/slim/document.html.slim#L130

(it appears it's using the highlight.js that's bundled with reveal.js)

**Comment by mojavelinux** [comment]
Oops, I see you are using deck.js. Then the location is here:

https://github.com/asciidoctor/asciidoctor-backends/blob/master/haml/deckjs/document.html.haml#L39

**Comment by danhyun** [comment]
I just realized what `backends` provides. I'll probably take a stab at this for deck.js and to upgrade reveal.js backend

**Comment by mojavelinux** [comment]
Many thanks in advance!

**Comment by aalmiray** [comment]
Given tha linked PR, is there anything else to be done from the plugin side?

**Comment by danhyun** [comment]
Sorry just realized this is filed in the wrong place, this is a backends issue not a plugin issue.
