### ISSUE TITLE
resources-copyspec creates wrong directory hierarchy

### ISSUE THREAD

**Issue by gernotstarke** [asciidoctor/asciidoctor-gradle-plugin#159]
within my asciidoctor task definition I define the following copySpec:

    resources {
        from("${srcDir}/images") {
          include '**'
        }
        into "$buildDir/images"
    }

This creates the build/html5/ directory,
but instead of adding an "./images" directory,
it creates a complete hierarchy:

    build/html5/Users/myUserName/myProjectDir/myProjectName/build/html5/images

**Comment by gernotstarke** [comment]
it works fine when I configure:

    resources {
        from("${srcDir}/images") {
          include '**'
        }
        into "./images"
    }

**Comment by aalmiray** [comment]
Yes, that's what I was about to say. You don't have to specify "$buildDir" in the target directory as the task already knows the root target path.

**Comment by gernotstarke** [comment]
I opened the issue as the gradle-documentation of "copySpec" contains explicit references to "$buildDir"... maybe you include the "into..." clause into the documentation :-)

kind regards - Gernot

**Comment by aalmiray** [comment]
Oh I see. It makes sense to show an example in the README.

**Comment by aalmiray** [comment]
Closed due to #160 is merged
