### ISSUE TITLE
Asciidoctor plugin seems to require users define an `asciidoctor` Configuration

### ISSUE THREAD

**Issue by sebersole** [asciidoctor/asciidoctor-gradle-plugin#164]
I get the following exception trying to upgrade from 0.7.o to 1.5.2:

```
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'asciidoctor' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:81)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:210)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:71)
        at org.gradle.api.internal.artifacts.configurations.ConfigurationContainerInternal$getByName.call(Unknown Source)
        at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:562)
```

AsciidoctorTask contains the following call at line 562:

```
if (classpath == null) {
    classpath = project.configurations.getByName(AsciidoctorPlugin.ASCIIDOCTOR)
}
```

The `getByName` (by design) requires that the name you look for must exist.  Is that really the intent?  Is there not a default version of Asciidoctor associated with a particular version of the plugin?    If not, perhaps you meant to instead use `findByName` or `maybeCreate`?

**Comment by sebersole** [comment]
FWIW, just adding an empty `asciidoctor` Configuration to my build does not help.  So it seems clear that the plugin is expecting me to define the asciidoctor artifact I want to use (depend on).  Would be nice if that was documented...

**Comment by ysb33r** [comment]
Do you have a copy of your build.gradle somewhere - this does not look right. A lot has changes between 0.7 and 1.5.2. It might be that something is still missing from your build.gradle fie.

**Comment by sebersole** [comment]
It is still in flux.  Here is the original working build (0.7.0): https://github.com/hibernate/hibernate-orm/blob/master/documentation/documentation.gradle

Here is the working build so far: https://gist.github.com/sebersole/e719cf603dc712306cdc

**Comment by sebersole** [comment]
Notice the line (https://gist.github.com/sebersole/e719cf603dc712306cdc#file-gistfile1-txt-L48) :

```
	asciidoctor 'org.asciidoctor:asciidoctorj:1.5.2'
```

I had to add that to get the build to work.  Without specifying any asciidoctor Configuration, I listed the exception.  Adding just the empty asciidoctor Configuration led to an error finding Asciidoctor classes (`java.lang.ClassNotFoundException: org.asciidoctor.Asciidoctor$Factory`).  So it seems pretty clear the plugin as-is is requiring that users specify which Asciidoctor version to use.

**Comment by sebersole** [comment]
IMO, a better option is to define an asciidoctor version on the plugin itself (it does, but just for tests atm) and use that as the fallback.

**Comment by ysb33r** [comment]
You seem to missing `apply plugin : 'org.asciidoctor.convert'`, which is probably the start of  most of the problems you are seeing.

**Comment by sebersole** [comment]
I dont (think I want to) apply the plugin.  I have an atypical set up in that I need to separately render multiple directories.

**Comment by ysb33r** [comment]
>  need to separately render multiple directories.

This can easily be done in 1.5.2. Just define multiple `AsciidoctorTask` instances and specify a different `outputDir` for each. Note that by default it will automaticaaly write different backends to different directories below the `outputDir`.

**Comment by sebersole** [comment]
Ok, I will try.  So it does not "auto define" a AsciidoctorTask?  As far as backends, I only render one and already disabled separateOutputDirs.

**Comment by ysb33r** [comment]
Ity auto-defines the default `asciidoctor` task. You can just add additional Asciidoctor tasks. IIRC in 1.5.1 or 0.7 there was a bug where only one task could be defined, unless a workaournd was added. In `1.5.2` that was all fixed.

If you don't like the default task being there just disable it with `asciidoctor.enabled=false` and only use the AsciidoctorTask instances you defined yourself.

**Comment by sebersole** [comment]
Awesome.  That all worked.  Thanks @ysb33r
