### ISSUE TITLE
`project.buildDir` is ignored

### ISSUE THREAD

**Issue by pniederw** [asciidoctor/asciidoctor-gradle-plugin#168]
Generated files always go into `build`, even if `project.buildDir` is set to a different directory.

**Comment by ysb33r** [comment]
Mmm... that's obviously a bug. I assume yousaw this when using the default `outputDir`

**Comment by mojavelinux** [comment]
Could the problem be that the `outputDir` is set too early? It's currently set in the task constructor as:

```groovy
outputDir = new File(project.buildDir, 'asciidoc')
```

As a workaround, you can set the `outputDir` explicitly in the task configuration. That should allow you to recompute it with the correct context.

**Comment by ysb33r** [comment]
I noticed that too @mojavelinux.

**Comment by pniederw** [comment]
As of Gradle 1.x/2.x, the standard way to initialize a property that depends on another model property is convention mapping: `task.conventionMapping.outputDir = { new File(project.buildDir, 'asciidoc') }` in the plugin. This will defer evaluation of the property until it's requested, after my build script has set `buildDir`.

**Comment by persillie** [comment]
I created a test to reproduce the behaviour, #171
