### ISSUE TITLE
Need ability to turn off automatic addition of jcenter

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#174]
In most cases people will not notice that `jcenter()` is automatically added when the plugin is applied. However there are cases when this behaviour is detrimental. 

1. When no external repositories are allowed.
2. In offline unit testing when testing needs to be against a specific disk-based repository

To this eefect I suggest an additional property on the `asciidoctorj` extension in a similar fashion that was done for the `jruby-gradle-base` plugin

```groovy
asciidoctorj {
  // Default will be false
  noDefaultRepositories = true
}
```

**Comment by aalmiray** [comment]
:+1:
