### ISSUE TITLE
Bump asciidoctorj-groovy-dsl version to 1.0.0.Alpha1

### ISSUE THREAD

**Issue by kubamarchwicki** [asciidoctor/asciidoctor-gradle-plugin#176]
Hi, 
There is an Alpha1 asciidoctorj-groovy-dsl version which has slightly different API (see this issue: asciidoctor/asciidoctorj-groovy-dsl#1). 

It brings confusion as methods described on the DSL manual doesn't work with the version of gradle plugin unless you explicitly define other DSL (for example `block_macro`)

I don't feel proficient enough with gradle to be sure only a changing [this line](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/src/main/groovy/org/asciidoctor/gradle/AsciidoctorExtension.groovy#L26) is needed - so I refrain from pull request

Kuba

**Comment by mojavelinux** [comment]
I'm pretty sure that will do it. We should definitely make that switch.

**Comment by aalmiray** [comment]
Fixed.
