### ISSUE TITLE
Using table cell inline styling renders TOC into cell

### ISSUE THREAD

**Issue by madmas** [asciidoctor/asciidoctor-gradle-plugin#177]
Hi,
recently the following strange effect popped up in one of my projects:
having a document like https://gist.github.com/madmas/02bbd962e213ec56c04e and rendering it with https://gist.github.com/madmas/8786fa4664994683cecc results in a TOC rendered into the cell I marked by a| to contain asciidoc content, screenshot: 
![bildschirmfoto 2015-11-11 um 10 51 43](https://cloud.githubusercontent.com/assets/37251/11088461/ba55e768-8862-11e5-9fe0-a482b2030e66.png)

Interesting thing is that it was woking (not shoing the undesired TOC) until ~2 weeks ago and my git history shows no changes to the build.gradle.

Any hints where this might be coming from?

**Comment by aalmiray** [comment]
The problem cannot be reproduce with `asciidoctor-gradle-plugin:1.5.2` but appears when `asciidoctor-gradle-plugin:1.5.3` is used. `asciidoctor-diagram:1.2.1` pulls in `asciidoctor:1.5.3`

    gems
    \--- rubygems:asciidoctor-diagram:1.2.1
            \--- rubygems:asciidoctor:[1.5.0,1.5.99999] -> 1.5.3

this appears to be a bug in Asciidoctor 1.5.3. //cc @mojavelinux @ysb33r

**Comment by mojavelinux** [comment]
This is indeed a regression in core. I did not think of this scenario when I added the toc support to the embedded node.

See https://github.com/asciidoctor/asciidoctor/issues/1582

**Comment by mojavelinux** [comment]
To workaround the issue, it's necessary to unset the `toc` attribute *below* the document header.

```
= Document Title
Author Name
:toc: right

:toc!:

content
```

The placement of the blank line above the `:toc!:` line is significant.

Btw, in the example you gave, you have blank lines below the document title before the attributes. There should never be blank lines between the document title and the header attributes. In this case, we use a blank line because we want to unset the `toc` attribute after the header is processed.

**Comment by madmas** [comment]
thanks a lot for the feedback and the workaround!

**Comment by russel** [comment]
@mojavelinux  @aalmiray  I am told that this bug is stopping the upgrade from 1.5.2 to 1.5.3 in the Groovy source and thus stopping the building of Groovy documentation on JDK9. Any news on progress fixing this?

**Comment by mojavelinux** [comment]
Keep in mind that the Gradle plugin is not restricted to a single version of AsciidoctorJ. You can set which version of AsciidoctorJ you would like to use. The Gradle plugin simply selects a version it prefers by default. See https://github.com/asciidoctor/asciidoctor-gradle-plugin#configuration

**Comment by mrotteveel** [comment]
To be more explicit, you can fix this by adding the following to `build.gradle`:

``` {.gradle}
repositories {
    jcenter()
}

asciidoctorj {
    version = '1.5.4'
}
```
