### ISSUE TITLE
Custom resources not copied

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-gradle-plugin#178]
Following along with the asciidoctor manual, I've tried to apply my own custom stylesheets as follows:

Project structure

``` bash
src
  /asciidoc
    main.adoc
  /resources
    /styles
      coderay-asciidoctor.css
      asciidoctor.css
      colony.css
```

In build.gradle

``` groovy
asciidoctor {

  sourceDir "src/asciidoc"
  resources {
    from ("src/resources") {
      include '**'
    }
  }
...
```

Then in main.adoc, my header info looks like this:

``` asciidoc
= Manual
me <me@example.com>
2015-12-28
:revnumber: {project-version}
:linkattrs:
:stylesdir: styles/
:stylesheet: colony.css
:linkcss:
```

The `asciidoctor` target fails with

``` bash
(Errno::ENOENT) < projectPath >l/build/asciidoc/html5/styles/coderay-asciidoctor.css
```

And the styles directory is not copied into the buildDir.

but If i copy the styles directory to the build dir manually, and then invoke the build, the build succeeds and keeps succeeding until I do a `clean`.  And, the info in styles does get copied each time I build the `asciidoctor` target.

So it seems like the resource processing should occur earlier in the asciidoc target.

Is there a bit of gradle mojo that I can do to force a change in processing order?

Is this something that can be (and should be) fixed in the plugin?

**Comment by kastork** [comment]
This does the trick, but I don't think it should be necessary.

```groovy
task copyResources(type: Copy) {
  from ("src/resources") {
    include '**'
  }
  into("${buildDir}/asciidoc/html5")
}
asciidoctor.dependsOn copyResources
```

**Comment by mojavelinux** [comment]
I think the resources need to be copied before Asciidoctor is run. Though
maybe before & after just in case an extension creates a new resource?

**Comment by kastork** [comment]
@mojavelinux yeah, that's what my workaround does.  It just doesn't feel natural in gradle-land to have to arrange for this explicitly.

**Comment by ysb33r** [comment]
I'm aware of this issue. Came across it some weeks ago playing with reveal.js and custom stylesheets. You've got the correct workaround for now.

**Comment by jochenchrist** [comment]
+1

However workaround is fine for now.
