### ISSUE TITLE
Add integration/functional tests

### ISSUE THREAD

**Issue by pledbrook** [asciidoctor/asciidoctor-gradle-plugin#180]
With the introduction of the Gradle TestKit, it's now fairly straightforward to test a variety of simple and complex Asciidoctor builds via integration or functional tests. Some things to consider:
- Such tests understandably run much more slowly than your usual unit tests. They can be part of the unit test suite, in which case it might make sense to mark them as slow via Spock annotations, or put them in a new integration test source set.
- IntelliJ doesn't particularly like integration test source sets. It always seems to mess up the dependencies, resulting in "class not found" errors in the source files for the integration tests.
- The [recommended approach](https://docs.gradle.org/2.10/userguide/test_kit.html#testKitFunctionalTestSpockClassesTestConfig) for getting the plugin onto the test builds' classpaths basically precludes running the tests from the IDE.

The biggest decision to make is whether to introduce a new source set for these tests or not. Thoughts?

**Comment by pledbrook** [comment]
I'm going to add ideas for other integration tests here:

* Ensure the incremental build works

**Comment by manuelprinz** [comment]
I'll also add an idea:

It would also be nice to run integration tests against all supported Gradle versions (or the latest patch-level version of each minor release). [GradleTest](https://gitlab.com/ysb33rOrg/gradleTest) could be used for that. The developer documentation should mention how to "disable" them to keep the feedback cycle fast.

**Comment by ysb33r** [comment]
There are now some on the 1.5.x line and some more on the 2.0.x line
