### ISSUE TITLE
Memory leak on multi-project builds

### ISSUE THREAD

**Issue by arming9** [asciidoctor/asciidoctor-gradle-plugin#182]
Dear developers, 

I'm facing a memory leak issue when building with the asciidoctor plugin in a multi-project scenario.  Dependening on the JVM used it happens sooner or later. I've put together a verification project to reproduce the issue:

My project build.gradle is:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
    }
}

```

My settings.gradle is:

```
for(int n = 0; n < 30; n++) {
    def projectname = 'prj-'+n
    def newprojectdir = new File(rootDir, projectname)
    newprojectdir.mkdirs()
    new File(newprojectdir, 'build.gradle').text = '''
        repositories {
            jcenter()
        }
        apply plugin: 'org.asciidoctor.convert'
    '''.stripIndent()
    def ascidocroot = new File(newprojectdir, 'src/docs/asciidoc')
    ascidocroot.mkdirs()
    new File(ascidocroot, 'test.adoc').text = '''
        HELLO
        ===================
        :Author Initials: AC

        HELLO WORLD!!!

    '''.stripIndent()

    include projectname
}
```

This will create a multi-project build with 30 subprojects and each doing asciidoctor.
Start the build with 

gradlew clean asciidoctor

Running on JDK8, you will have to 
SET GRADLE_OPTS=-Xmx168m -Xms168m -Xss1m
in order to get straight to the leak.

My Gradle version is 2.10

In JDK6 and 7, you'll end up with a PermGenSpace OutOfMemory error after 3-5 projects, 
In JDK8 it takes a little more (therefore restrict the memory with GRADLE_OPTS, otherwise the JVM grows without limit).

**Comment by manuelprinz** [comment]
Although this is a really old bug, I was able to reproduce it under Java 8 with Gradle 2.10, 3.5.1 and 4.5.1.

**Comment by ysb33r** [comment]
Thanks. I am not going to look at this for 1.5.x, but it will be worthwile to create a manual test for this to test whether the same problem occurs for 2.0.x

**Comment by ysb33r** [comment]
A test has been added to 2.0 to check for this and will be in the 2.0-alpha.3 codebase. It has to be executed manually for now.
