### ISSUE TITLE
PDF Backend fails when Attributes are specified

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-gradle-plugin#183]
I created a custom pdf theme, which I can use by calling `asciidoctor-pdf` as described in the theming guide.

I try to use that in a Gradle Build, with the following set:

```
asciidoctor {
    backends 'pdf'
    sourceDir = new File(".")
    attributes 'pdf-stylesdir': 'resources/themes',
            'pdf-style': 'mycustomstyle'
}
```

The Build fails. I used `--debug` to get the executed `asciidoctor` line, and tried it by hand:

```
$ asciidoctor -B /path/to/project -b pdf -a pdf-stylesdir=resources/themes -a pdf-style=mycustomstyle -a projectdir -a rootdir -a project-name=mydoc -a project-group -a project-version=unspecified /path/to/doc.adoc 
asciidoctor: FAILED: missing converter for backend 'pdf'. Processing aborted. (RuntimeError)
  Use --trace for backtrace
```

If I add `-r asciidoctor-pdf`, it works, cf http://asciidoctor.org/docs/convert-asciidoc-to-pdf/#convert-asciidoc-to-pdf

I think this is a bug in the gradle plugin. Or do I need to change my `build.gradle` file? Is there a workaround for this?

EDIT: Note that it works fine if I remove the `attributes` clause from the Gradle Build file.

**Comment by mojavelinux** [comment]
> missing converter for backend 'pdf'

Seems like you are missing the AsciidoctorJ PDF jar.

If you do have that, try adding "requires" to the task configuration as described here: https://github.com/asciidoctor/asciidoctor-gradle-plugin#usage (though I don't think that should be necessary in the case of the pdf backend).

**Comment by fwilhe** [comment]
Does not work for me..

What is the name of the module for the `requires` clause? `asciidoctor-pdf`? `pdf`? `Pdf`? I tried those, without success.

To recap, here is my full `build.gradle`:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.6'
    }
}

plugins {
    id 'org.asciidoctor.convert' version '1.5.3'
}

apply plugin: 'org.asciidoctor.convert'

asciidoctor {
    backends 'html5', 'pdf'
    sourceDir = new File(".")
    attributes 'pdf-stylesdir': 'resources/themes',
            'pdf-style': 'mycustomstyle'
}

defaultTasks 'asciidoctor'
```

Adding `requires 'asciidoctor-pdf'` or something similar to the `asciidoctor` closure should do the job, right?

**Comment by fwilhe** [comment]
All right, I checked the version of `asciidoctorj-pdf` and found that I got it from http://mvnrepository.com/artifact/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.6 yesterday (was my second google hit, right after the github repo..) , which is obviously not the latest version. I tried with `alpha.11` and this works, without requiring anything in the gradle file.

Sorry for not checking that in advance.

Case closed.

**Comment by mojavelinux** [comment]
\o/

Sorry you got hung up on that.

For future reference, I think this example covers your use case.

https://github.com/asciidoctor/asciidoctor-gradle-examples/blob/master/asciidoc-to-pdf-example/build.gradle

(though it could stand to be updated)
