### ISSUE TITLE
Extension  block_macro() not supported ?

### ISSUE THREAD

**Issue by davidB** [asciidoctor/asciidoctor-gradle-plugin#193]
Hi,

I'm new into asciidoctor, so maybe I did a miss configuration, but when I try to declare a block_macro the build failed. (it works with the sample bock())

```
./gradlew clean asciidoc
:clean
:asciidoctor FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/davidb/tmp/sandbox_jme_wiki/sandbox_wiki_jme/build.gradle' line: 37

* What went wrong:
Execution failed for task ':asciidoctor'.
> Could not find method block_macro() for arguments [{name=iframe}, build_5c1dmp5gvj1ykvv0yf67pkgtt$_run_closure2$_closure6$_closure7@46de1668] on root project 'sandbox_wiki_jme'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.433 secs
```

And the build.gradle fragment:

```
asciidoctor {
    resources {
        from('src/docs/images')
    }
    resources {
        from('src/docs/resources')
    }
    attributes 'build-gradle': file('build.gradle'),
        'sourcedir': project.sourceSets.main.java.srcDirs[0],
        'endpoint-url': 'http://davidb.github.io/sandbox_wiki_jme',
        'source-highlighter' : 'coderay',
        'linkcss': 'true',
        //'imagesdir':'/images',
        'toc':'left',
        'icons': 'font',
        'setanchors':'true',
        'idprefix':'',
        'idseparator':'-',
        'docinfo1':'true',
        'orgname':'jMonkeyEngine'
    options header_footer: true,
        template_dirs: [file('src/templates/slim').absolutePath]
    extensions {
        block_macro(name: 'iframe') {
            parent, target, attributes ->
            String content = """<iframe src="${target}"></iframe>""";
            createBlock(parent, "pass", [content], attributes, config);
        }
    }
}
```

**Comment by abelsromero** [comment]
First, apologies, the DSL module is still in alpha and there's been some changes in some method names and that's not clear in the documentation.
The error appears because the asciidoctor-gradle-plugin is not using the last source of the DSL in which 'blockmacro' was replaced by 'block_macro' to align it the core Ruby module of Asciidoctor.

To fix it, just remove the underscore from the method name (use 'blockmacro') and your extension will work.
Reminder, the DSL module for extensions is Alpha, so if you see anything that could be improved feel free to open an issue in the project https://github.com/asciidoctor/asciidoctorj-groovy-dsl. All feedback is welcome :)

**Comment by mojavelinux** [comment]
It's also possible to tell the plugin to use the latest release, right?

```
asciidoctorj {
  groovyDslVersion = '1.0.0.Alpha1'
}
```

This needs to be documented in the README, so I'm going to mark this as a documentation issue.

**Comment by abelsromero** [comment]
> It's also possible to tell the plugin to use the latest release, right?

I think so, but I am not sure if the changes have been published and what is published right now...
The history for the version file shows no [changes](https://github.com/asciidoctor/asciidoctorj-groovy-dsl/commits/master/gradle.properties).
The Alpha1 release was published on 1st April 15 (according to bintray), but the block_macro method was added on the 25th March 15. In theory it should be present, but I tested it and is not.

@robertpanzer can you help?

**Comment by mojavelinux** [comment]
That configuration setting may not yet be available in a released version of the plugin. If I add the dependency explicitly, it works:

```
    classpath('org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.Alpha1') {
      exclude group: 'org.codehaus.groovy', module: 'groovy-all'
      exclude group: 'org.asciidoctor', module: 'asciidoctorj'
    }
```

**Comment by ysb33r** [comment]
Use 2.1.0 of the plugin.
