### ISSUE TITLE
Can't pass :last-update-label!: attribute from Gradle

### ISSUE THREAD

**Issue by graemerocher** [asciidoctor/asciidoctor-gradle-plugin#194]
In order to reduce the size of commits for snapshots we want to not include the date on each document in the HTML output. To do this in an `adoc` file you do:

```
:last-update-label!:
```

But that requires modifying all `adoc` files. I have tried several ways to pass these parameter in as an attribute in the Gradle plugin but it does not seem to work.

**Comment by mojavelinux** [comment]
You can pass this parameter from the Gradle plugin. The equivalent in Groovy world to the ! is a null value.

```
asciidoctor {
  attributes 'last-update-label': null
}
```

**Comment by graemerocher** [comment]
That doesn't seem to work for me. I still see the "Last Updated" timestamp at the bottom.

**Comment by mojavelinux** [comment]
FYI, in the upcoming 1.5.5, we've added another way to do this through the use of the reproducible flag.

**Comment by graemerocher** [comment]
Sounds good.

**Comment by mojavelinux** [comment]
Correction. The reproducible flag is available in 1.5.4. So you can set:

```
asciidoctor {
  attributes 'reproducible': ''
}
```

**Comment by graemerocher** [comment]
Thanks, but 1.5.4 of the Gradle plugin doesn't seem to be out yet either.

**Comment by aalmiray** [comment]
If the `reproducible` flag is found in Asciidoctor (Ruby) and/or Asciidoctorj then you don't need a new version of the gradle plugin. What you can do is change the asciidoctorj version using the `asciidoctorj` extension block, for example

    asciidoctorj {
        version = '1.5.4'
    }

**Comment by graemerocher** [comment]
Gotcha

**Comment by graemerocher** [comment]
Confirmed that the `reproducible` solution works. Thanks.
