### ISSUE TITLE
Do not automatiically add Jcenter

### ISSUE THREAD

**Issue by jaredsburrows** [asciidoctor/asciidoctor-gradle-plugin#196]
See here: https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/a35280719e0643ed657e626245e7b8773e7f92fb/src/test/groovy/org/asciidoctor/gradle/AsciidoctorPluginSpec.groovy#L87

I like to use:
```
repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}
```
instead of:
```
repositories {
    jcenter()
    mavenCentral()
}
```

It would be nice if this plugin did not automatically add a `repositories` plugin.

**Comment by mojavelinux** [comment]
But there is a way to disable it. Are you suggesting that the default be reversed? Keep in mind, this repository is added in order to fetch AsciidoctorJ.

**Comment by ysb33r** [comment]
Yeah, that was PR #175. I'm not sure whether it made it into the last release.

**Comment by jaredsburrows** [comment]
@mojavelinux Yes, I just want to use a single repo.

@ysb33r Thanks. It works:

```
repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}

asciidoctor {
    description = project.description

    attributes "source-highlighter": "coderay",
            "linkcss": true,
            "title": project.name
}

asciidoctorj {
    noDefaultRepositories = true
}

task listrepos << {
    println "Repositories:"
    project.repositories.each { println "Name: " + it.name + "; url: " + it.url }
}
```

Output:
```
$ gradle listrepos
Incremental java compilation is an incubating feature.
:listrepos
Repositories:
Name: maven; url: https://plugins.gradle.org/m2/

BUILD SUCCESSFUL

Total time: 0.737 secs
```

**Comment by whbboyd** [comment]
I would like to register in the strongest possible terms that *defaulting* to modifying the project's repository setup is incorrect and unacceptable. If no repository with `asciidoctorj` is available, the resulting error message is clear and the resolution is obvious. On the other hand, if there is some reason not to want jcenter configured in a project's repositories, tracking down where it came from is massively, excessively difficult.

Action at a distance is bad. Arguably Gradle shouldn't even allow this; but please don't take advantage of its laxness.

**Comment by ysb33r** [comment]
This is not the only plugin in the Gradle world where this has been done. Over time the community has learnt that this is not a good practice for public available plugins. The only place where this approach is still valid is in highly opinionated plugins - typically within an organisation.

At some stage the default inclusion of `jcenter` will be removed.

**Comment by mojavelinux** [comment]
Yep, it's been possible to disable the default repositories since 1.5.3.

See https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/release_1_5_6/src/main/groovy/org/asciidoctor/gradle/AsciidoctorExtension.groovy#L28-L35

I agree, though, that this default should either be reversed or the behavior should just be removed. I think the idea was to have a way to fetch additional packages to ease the first-time user experience. However, that's probably better accomplished using documentation (esp since you have to have the repositories defined to get the plugin in the first place).

**Comment by mojavelinux** [comment]
Regardless, we can't work off a closed issue. Therefore, @whbboyd, if you feel strongly about this, I recommend opening a new issue so action can be taken.

**Comment by aalmiray** [comment]
Added to `2.0.0` as this is a breaking change in behavior.
