### ISSUE TITLE
Document how to build and use a snapshot of a plugin

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-gradle-plugin#197]
To help contributors, testers, and early adopters participate in development, document how to build a snapshot of the plugin and use it in an existing Gradle build. This documentation should be added either to the README or a contributing guide.

I have outlined the steps in the following comment: https://github.com/asciidoctor/asciidoctor-gradle-examples/issues/13#issuecomment-239649980

**Comment by ehmkah** [comment]
We linked the documentation for contributing. What is needed that this issue can be closed?
