### ISSUE TITLE
Recursive include images

### ISSUE THREAD

**Issue by milefork** [asciidoctor/asciidoctor-gradle-plugin#200]
Hi,

I stumbled upon an issue:
When an adoc file out of a folder gets included which contains image links the reference to the image should be updated so that they can be shown.

Maybe take a look at this sample setup to explain my problem: https://www.dropbox.com/s/c8isczjnd35h78b/test.zip?dl=0

**Comment by mojavelinux** [comment]
You're not quite understanding how the imagesdir directive works. It has no awareness of the include file. When you think of includes, you need to think of the file completed expanded before the converter touches it. The converter only sees one, combined file.

What you are thinking of is subdocuments, which AsciiDoc / Asciidoctor does not yet support. We've discussed it quite extensively, but haven't yet arrived at a solution. See https://github.com/asciidoctor/asciidoctor-pdf/issues/93

**Comment by milefork** [comment]
@mojavelinux ah okay that's the point that subdocuments are not supported yet!

I'm quite understanding how the imagesdir attribute works but it was my plan that the images reside byside the adoc's and not in a seperate folder.
Nevermind I'll look forward to the support of subdocuments! :+1:

**Comment by ysb33r** [comment]
> but it was my plan that the images reside byside the adoc's and not in a seperate folder.

It is not clear whether you meant in the source or output directory.

If it is the source directory, you can override by doing 

```
resources {
  include '*.png'
}

**Comment by ysb33r** [comment]
Closing as there is no more tarction on this.
