### ISSUE TITLE
DSL 2.0 Reloaded

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#201]
Taking to @aalmiray here at DevoxxMA we were thinking of evolving the plugin
in a slightly different direction than to what was discussed previously in
#157 & #161.

@pledbrook 's experiments with the new software model has shown that is not quite up
to what we have planned and to a great extent the NSM has been placed on hold 
in the Gradle core team.

So out thinking in short consists of:

* Split into a `base` & `convert` plugins. The `base` plugin will provide all of the
  functionality, but no defaults such as the `asciidoctor task`
* The `asciidoctorj` extension will be removed
* Remove injection of `jcenter` as a repository.
* Create `asciidoctor` configuration and eliminate the internal `asciidoctorj_internal` extension
  that exists today.
* A default `asciidoctorj` dependency will be injected using the default dependencies API,
  but a user can specify a different version of `asciidoctorj` using the normal 
  maven coordinates. 
* Additional asciidoctor plugins can be specified in the `asciidoctor` configuration.   
* Create `AsciidoctorSpec` class which mostly follows the current configuration style of 
  the `asciidoctor` task as we know it today.
* Allow `AsciidoctorSpec` to consume other `AsciidoctorSpec` via a `with` method in
  a similar way to `CopySpec`.
* Restrict tasks to one backend per task. This is counter-balanced by the ability
  to create standalone `asciidoctorSpec` instances which can be shared between different
  `AsciidoctorTask` instances.
* An `asciidoctorSpec` extension will be added to the `project` object in a similar
  fashion to the `copySpec` method.  
* Support extensions with an AsciidoctorTask via `extensions` or in a global manner via `asciidoctorExtensions`. (This should also take casre of #166).

Obviously there will be a number of breaking changes and we argue that this should be
a `2.0` release, which no longer tracks the version of `asciidoctorj` directly.

Full support for plugins via GEMs will still be supported.

Below is a DSL snippet that captures our thoughts.

```groovy
 
dependencies {
  asciidoctor 'org.asciidoctor:pdf:1.5.3'
}

ext {
  mySpec = asciidoctorSpec {
    attributes 'source-highlighter': 'coderay',
                toc                 : '',
                idprefix            : '',
                idseparator         : '-'  
    }
}

asciidoctorExtensions {
  // Creates a global asciidoctorExtension that will be available for usage in all
  // tasks.
  myExtension {
      block(name: "BIG", contexts: [":paragraph"]) {
          parent, reader, attributes ->
          def upperLines = reader.readLines()
              .collect {it.toUpperCase()}
              .inject("") {a, b -> a + '\n' + b}

          createBlock(parent, "paragraph", [upperLines], attributes, [:])
        }  
  }
}

apply plugin : 'org.asciidoctor.convert'

asciidoctor {
  backend 'html5'

   sources {
      include 'awesome.adoc'
   }  

   // Use the global extension
   extensions `myExtension`

   // Add a custom extension to task
   extensions {
     block(name: "BIG", contexts: [":paragraph"]) {
       parent, reader, attributes ->
       def upperLines = reader.readLines()
           .collect {it.toUpperCase()}
           .inject("") {a, b -> a + '\n' + b}

       createBlock(parent, "paragraph", [upperLines], attributes, [:])
     }     
   }
   with mySpec
}

**Comment by pledbrook** [comment]
Sorry for terseness. I think this proposal needs some rationale for the changes, particularly if they're going to break people's builds. The Asciidoctor specs looks interesting for sure. On the other hand, it feels like a missed opportunity to strengthen the model from the user's perspective.

For example, I think it would be nice to introduce the concept of a `Document` that has a set of sources attached to it, an attributes spec, and a set of backends. This model could then produce tasks of the form:

 - `processMyDocAsHtml5`
 - `processMyOtherDocAsPdf`
 - `processAllDocs`

I hate the word "process" here, but I don't want to spend too long thinking of a name :smile:

One more comment on this specific proposal: I don't really like to see "normal" code in build files, so would it be possible to allow extensions and post processors as classes in _buildSrc_?

**Comment by ysb33r** [comment]
Closing this as I'm working on something far better that this (IMO at least), which uses much newer functionality in Gradle. My experiment open on a #237 (a PR which is nor ready for merging).
