### ISSUE TITLE
Extension project dependencies don't create a task dependency on the other module

### ISSUE THREAD

**Issue by adrianjgeorge** [asciidoctor/asciidoctor-gradle-plugin#202]
When using:
```
dependencies {
  asciidoctor project(':some-extension')
}
```

The plugin is not correctly adding a dependency onto the jar task (or maybe another is more appropriate) of `:some-extension`. Which means the extension isn't necessarily built. Additionally there is no failure message when it can't resolve the dependency (since it hasn't been built), it just silently continues along making it really difficult to determine what the problem is.

**Comment by ysb33r** [comment]
I suspect we could solve this if we implement #201 as the use of classpath from configurations would be used to a greater extent rather than just searching for the existance of the asciidoctorj jar.

**Comment by eskatos** [comment]
See PR #212 for a failing integration test.

**Comment by ysb33r** [comment]
I think this is now solved in the 2.0 development. The way extensions are used as been re-written to a create extent to be a first-class integration rather than the bolt-on of the 1.5.x series. (See #240).
