### ISSUE TITLE
Please release an upgrade to asciidoctorj 1.5.5

### ISSUE THREAD

**Issue by jexp** [asciidoctor/asciidoctor-gradle-plugin#205]
The last update was 1.5.3 in November 2015, almost 18 months ago.

Thank you!

**Comment by aalmiray** [comment]
There's no need to update the plugin immediately as you can run the current version with any `asciidoctorj` version. The readme shows how in the **Configuration** section, for example

    asciidoctorj {
        version = '1.5.5'
    }

Upgrading to 1.5.5 and making a new release helps in those cases where custom configuration is not added and yet the developer wants the latest release 😏

**Comment by mojavelinux** [comment]
I think it's worth upgrading the plugin, even if it's just to change the default versions that are used. (This is a strategy followed by most Gulp plugins). However, rather than do it now, I recommend waiting until 1.5.6 is released later this week since we'd just have to turn right back around and do it again.

**Comment by mojavelinux** [comment]
Btw, the reason I make this case is that it takes less time to do a release than to answer support requests asking about how to change the default version. So it's really a matter of economics.

**Comment by mojavelinux** [comment]
On top of that, we get a chance to drum up publicity for the plugin :)

**Comment by mojavelinux** [comment]
Shall we update the title to say "1.5.6"?

**Comment by aalmiray** [comment]
Asciidoctorj version bumped to `1.5.5`, awaiting `1.5.6` to be released 😏

**Comment by mojavelinux** [comment]
I'm working hard to get 1.5.6 released. I just solve one of the last big issues, so what's left after that is the home stretch.

**Comment by sdeleuze** [comment]
@aalmiray Now that 1.5.6 is released, could you please publish it to https://plugins.gradle.org/plugin/org.asciidoctor.convert ?

**Comment by aalmiray** [comment]
we have a Hackergarten meeting on Wednesday evening, I'll check what's needed for a release tomorrow.

**Comment by aalmiray** [comment]
Fixed in release 1.5.6
