### ISSUE TITLE
Latest releases not available in gradle plugin portal

### ISSUE THREAD

**Issue by w25r** [asciidoctor/asciidoctor-gradle-plugin#206]
The latest release in Gradle's plugin portal is 1.5.1.

https://plugins.gradle.org/plugin/org.asciidoctor.gradle.asciidoctor

Would you mind publishing to the portal as well as JCenter?  

Thanks!

**Comment by eskatos** [comment]
Hi @w25r,
Starting with `1.5.2`,  the plugin moved to `id("org.asciidoctor.convert")`
See https://plugins.gradle.org/plugin/org.asciidoctor.convert
