### ISSUE TITLE
Resources should be copied before invoking the backend

### ISSUE THREAD

**Issue by alkemist** [asciidoctor/asciidoctor-gradle-plugin#208]
I'm using the coderay syntax highlighter, and it wants its CSS in place before invocation. The error I saw was:

```
> Task :user-docs:build-scan-plugin-user-manual:asciidoctor
May 24, 2017 2:31:53 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SEVERE: (Errno::ENOENT) /Users/ld/Projects/dotcom/user-docs/build-scan-plugin-user-manual/build/asciidoc/html5/css/coderay-asciidoctor.css
```

I patched the plugin to copy resources before processing, and everything was A-OK.

**Comment by ysb33r** [comment]
We need to check compatibility of this fix with asciidoctorj-diagram. Default setup of something like `[ditaa]` drops the images in the `images` source folder IIRC. Thus copying resources first could break this behaviour.
