### ISSUE TITLE
Plugin fails on generating PlantUML diagram

### ISSUE THREAD

**Issue by eshepelyuk** [asciidoctor/asciidoctor-gradle-plugin#211]
Using [example repository](https://github.com/asciidoctor/asciidoctor-gradle-examples/tree/master/asciidoc-diagram-to-html-example) and executing
 
    $ ./gradlew clean asciidoctor

I'm getting and error

```
:asciidoc-diagram-to-html-example:asciidoctor(NoMethodError) asciidoctor: FAILED: D:/projects/asciidoctor-gradle-examples/asciidoc-diagram-to-html-example/src/docs/asciidoc/example-manual.adoc: Failed to load AsciiDoc document - undefined method `empty?' for nil:NilClass
asciidoctor-diagram: ERROR: Failed to generate image: undefined method `empty?' for nil:NilClass
```

Full stacktrace attached
[error.txt](https://github.com/asciidoctor/asciidoctor-gradle-plugin/files/1145084/error.txt)

### P.S. 

The reason is version of `AsciiDoctor` GEM, i.e. `1.5.6`.
When using `1.5.5` everything is working fine.

**Comment by mojavelinux** [comment]
After the release, we discovered that Asciidoctor 1.5.6 is not compatible
with Asciidoctor Diagram 1.5.4. A new release of Asciidoctor Diagram is on
the way. Stay tuned.
