### ISSUE TITLE
asciidoctor-gradle-plugin 1.5.6 is not fully Java7 compatible

### ISSUE THREAD

**Issue by jjohannes** [asciidoctor/asciidoctor-gradle-plugin#218]
Unfortunately, Java 8 API sneaked into the code with this PR:
https://github.com/asciidoctor/asciidoctor-gradle-plugin/commit/0b9d614fb10fcf79747588e0a8257fca5b96033a#diff-467e6edfd5f5943cc0fdf8e11457f034R865

`Map.computeIfAbsent()` is not available in Java 7.

**Comment by jjohannes** [comment]
@aalmiray Thanks for fixing this! Do you plan do release a new version with the fix anytime soon?

**Comment by manuelprinz** [comment]
If I saw correctly, this is not released yet. Maybe have a 1.5.7?

**Comment by ysb33r** [comment]
It is in 1.5.7.
