### ISSUE TITLE
plugin 1.5.6 incremental build with asciidoctorj-diagram

### ISSUE THREAD

**Issue by gregallen** [asciidoctor/asciidoctor-gradle-plugin#220]
this works fine on a clean build, but on the next build, where only a adoc containing a diagram is updated, it fails with an error relating to ditaa, as if the diagram requires didn't get applied

**Comment by abelsromero** [comment]
It seems to be it is related to how the extensions are loaded and the gradle daemon. Did you add the diagram extension using the `asciidoctor` configuration like here https://github.com/asciidoctor/asciidoctor-gradle-plugin#adding-custom-extensions?

If you did, please, can you add some example or provide more details?

**Comment by gregallen** [comment]
yes, I am using the daemon.
yes, I was adding asciidoctor-diagram to the classpath as shown. Curiously I was originally adding it using the buildscript classpath, though that had exactly the same issue.
Please note that I am seeing this issue with gradle 2.12. I'm not able to upgrade that.
I can trivially working around by reverting to plugin 1.5.3

**Comment by abelsromero** [comment]
You mean you get this right?

```
11:41:26: Executing external task 'asciidoctor'...
asciidoctor: WARNING: example-manual.adoc: line 55: invalid style for listing block: ditaa
:asciidoctor
```

**Comment by gregallen** [comment]
yes, exactly that. the ditaa diagram goes unprocessed, left rendered as <pre>, as if I hadn't added diagram to the requires

**Comment by gregallen** [comment]
presumably the _requires_ property needs to be used in AsciidoctorProxyCacheKey and the requires loaded when the proxy is created? Hence the requires will then only be loaded once.

**Comment by abelsromero** [comment]
I could confirm that the issue does only happen with 1.5.6, not with 1.5.3 and gradle 2.12 and gradle 4.3.
But I haven't had time to look into the code changes, v 1.5.3 skiped to 1.5.6, should be easy to spot what broke it.
I wont' have much time until next week, so If you already spot the problem and want to have a try, feel free so send a PR.

**Comment by bobpiece** [comment]
Is there any chance for fixing this issue?

**Comment by iwan-aucamp-cs** [comment]
I'm pretty sure this is same issue as #222 - there is a workaround there.

**Comment by ysb33r** [comment]
Closing this, but tracking in #222 as this is the same problem
