### ISSUE TITLE
Using xrefstyle with asciidoctor-gradle-plugin

### ISSUE THREAD

**Issue by k-mack** [asciidoctor/asciidoctor-gradle-plugin#221]
I would like to use the new xrefstyle feature in Asciidoctor and be able to build the document using this Gradle plugin. Using the latest asciidoctorj via the CLI, I get the expected `xrefstyle` output. `xrefstyle` seems to be ignored by this plugin.

### Expected Behavior

The `xrefstyle` attribute is processed and applied correctly such that this plugin's output looks as if it was produced by asciidoctorj via the CLI:

```
java -cp asciidoctorj-1.6.0-alpha.6.jar;jcommander-1.35.jar;jruby-complete-9.1.14.0.jar org.asciidoctor.cli.AsciidoctorInvoker test.adoc
```

### Current Behavior

The `xrefstyle` attribute seems to be ignored.

### Context

Given build.gradle and test.adoc,

```gradle
// build.gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.6'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16'
        classpath 'org.jruby:jruby-complete:9.1.14.0'
    }
}

apply plugin: 'org.asciidoctor.convert'

asciidoctorj {
    version = '1.6.0-alpha.6'
}

asciidoctor {
    description = 'Generate documentation.'
    group = 'documentation'
    sourceDir 'src/docs/asciidoc'
    outputDir 'build/docs/asciidoc'
    backends = ['html5','pdf']
}
```

```adoc
// test.adoc
= Document
:listing-caption: Listing
:xrefstyle: short

== Section

<<my-listing1>>

[[my-listing1]]
.Declare a String in Java
[source,java]
----
String s;
----
```

When `gradlew asciidoctor` is ran, then the content is produced as if `xrefstyle` is ignored (or set to `basic`):

![screenshot-2017-11-21 document](https://user-images.githubusercontent.com/2957142/33086942-358bb89e-ceb7-11e7-9d3a-edd75af2b92b.png)

However, running asciidoctorj on the same input file via the CLI (as shown in **Expected Behavior**) produces:

![image](https://user-images.githubusercontent.com/2957142/33087275-191ad162-ceb8-11e7-9e48-9f25156ce8dc.png)

**Comment by mojavelinux** [comment]
Check the Asciidoctor core version in use by adding the following to the document:

```
{asciidoctor-version}
```

If that isn't at least 1.5.6, it isn't going to work.

It seems like the version of AsciidoctorJ 1.5.5 being pulled in by AsciidoctorJ PDF is overriding the version of AsciidoctorJ you have specified. Try:

```
classpath('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16') {
    exclude group: 'org.asciidoctor', module: 'asciidoctorj'
}
```

However, when I try that, then I get:

```
(NameError) Treeprocessor not found in packages org.asciidoctor.extension; last error: cannot load Java class org.asciidoctor.extension.Treeprocessor
```

Something seems really wrong with this plugin atm.

**Comment by mojavelinux** [comment]
Here's a script that works:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.6'
        classpath 'org.asciidoctor:asciidoctorj:1.6.0-alpha.6'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16'
        classpath 'org.jruby:jruby-complete:9.1.15.0'
    }
}

apply plugin: 'org.asciidoctor.convert'

asciidoctor {
    description = 'Generate documentation.'
    group = 'documentation'
    sourceDir 'src/docs/asciidoc'
    outputDir 'build/docs/asciidoc'
    backends = ['html5','pdf']
}
```

Setting the version of AsciidoctorJ using the DSL is unreliable atm. You need to configure the version in the buildscript classpath.

**Comment by k-mack** [comment]
@mojavelinux Thanks for the help on this!
