### ISSUE TITLE
Moving to Gradle 4.x?

### ISSUE THREAD

**Issue by manuelprinz** [asciidoctor/asciidoctor-gradle-plugin#227]
Hi all,

I was wondering about the state of the plug-in and if there are any plans to upgrade Gradle to a 4.x version? The reason being that I have more and more problems using it with current Gradle versions. Using it with the [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) is hard and broken for a lot of features. (My PRs fix only a small part of it.) I would really like to contribute fixes but those would require APIs introduced by Gradle 4. It would also mean re-writing larger parts of the code. (Although they would likely become smaller and easier to test.) I'm also convinced that some of the open issues can be fixed in the process.

I'd appreciate any guidance on how to proceed with this, such as how API versioning is done, how you organize these changes, do reviews, etc.

Thanks for all the hard work you put into the plug-in already! I use it daily and it rocks!

Best,

Manuel

**Comment by aalmiray** [comment]
Hi Manuel, we can't move to Gradle 4.x just yet as we don't have information on how many people are still using Gradle 2 and 3 in combination with this plugin. As a matter of fact we had to rollback a fix in the latest release as a 4.x feature was being used and some of of our users complained the plugin was no longer usable for them.

We could perhaps schedule `2.0.0` to have Gradle 4.x as minimum version and keep `1.x` as Gradle 3 compatible.

**Comment by manuelprinz** [comment]
Hi Andres,

thank you for replying! Yes, I already tried to find some data on Gradle version used in the wild but this does not seem to be publicly available.

Scheduling this for 2.0 seems like a good idea. What would be the way forward? Creating issues, a milestone and a dedicated branch, like `development-2.0`? Should I do this in my fork or would you be willing to give me some basic rights to the repository?

Best,

Manuel

P.S.: Sorry for asking such basic questions, but I do not know how you organize development of the plug-in.

**Comment by aalmiray** [comment]
Hi Manuel,

No worries, on the contrary, thank you for showing interest in the project and submitting issues/patches 😄 

Creating separate issues and a `2.0.0` milestone would be the way to go. I'd recommend creating a feature branch per issue on your fork, then submit a PR for each feature as it becomes ready. I know it's a bit of a hassle to submit more than one PR but in this way we can keep the code short and to the point. What do you think?

**Comment by manuelprinz** [comment]
I am totally  fine with that! I prefer to "blend in" and don't want to disrupt the workflow you (or the project as a whole) follows. I also prefer short PRs, although sometimes it is a bit of a hassle if they depend on each other. But that can be explained in the messages.

Will you create the milestone? Is another 1.x planned? Maybe we should also have on for this.

My current plan was to spend some time on triaging/classifying and (hopefully) fixing some bugs. I see it as a chance to become more familiar with the code base (although I spent a good portion on that already). And create some new issues and code for the Gradle 4/5 tasks.

Does this work for you? BTW, where is the right place to ask questions about the code if they come up? Issues? Gitter? Mailing list?

Best,

Manuel

**Comment by aalmiray** [comment]
Milestone `2.0.0` is already available.
There are no plans for another release of the `1.x` unless a critical bug is found.
Asking questions here as issues is fine as others can interact as well, gitter is more of a generic asciidoctor kind of forum 😏

**Comment by manuelprinz** [comment]
Got it. :smile:
