### ISSUE TITLE
Fix AppVeyor build

### ISSUE THREAD

**Issue by manuelprinz** [asciidoctor/asciidoctor-gradle-plugin#228]
Currently AppVeyor fails on every build attempt which makes the results on merge requests less valuable and confusing for contributors.

**Comment by manuelprinz** [comment]
It seems like `net.ossindex.audit` is built against Java 8 which fails AppVeyor builds for Java 7. What would be the preferred solution? Drop build of Java 7 in AppVeyor? Or roll back to an older version of `net.ossindex.audit`?

**Comment by ysb33r** [comment]
We only build with JDK8 on Appveyor now, but we build 1.7 targetCompatibility.
