### ISSUE TITLE
Permissions for editing issues?

### ISSUE THREAD

**Issue by manuelprinz** [asciidoctor/asciidoctor-gradle-plugin#229]
Hi,

could I please get permissions to add milestones and tags to issues? I'd like to do some bug triaging and this would help with classification. Thanks in advance!

Best,

Manuel

**Comment by mojavelinux** [comment]
I support this request.

@aalmiray if you agree and want me to update the permissions for @manuelprinz, let me know.

**Comment by manuelprinz** [comment]
Any update on this?

**Comment by mojavelinux** [comment]
@manuelprinz You'll first need to accept the invitation to the organization, which I just sent. Look for an e-mail or go to https://github.com/asciidoctor to accept it.

**Comment by manuelprinz** [comment]
@mojavelinux Done. Thanks!

**Comment by manuelprinz** [comment]
@mojavelinux @aalmiray I am still not part of the project, just the organization, so not really able to work on bug triaging or similar. Could you please add me?

**Comment by mojavelinux** [comment]
I created the gradle-plugin-committers team and added you as a member. That should allow you to triage issues.

**Comment by manuelprinz** [comment]
@mojavelinux Thanks! :smile:
