### ISSUE TITLE
Extract settings into extension

### ISSUE THREAD

**Issue by manuelprinz** [asciidoctor/asciidoctor-gradle-plugin#231]
It is recommended by Gradle to use extensions for configuration. I started experimenting with it and extracted `sourceDir` to an extension. Code can be found in [my `gradle-4.x` branch](https://github.com/manuelprinz/asciidoctor-gradle-plugin/tree/gradle-4.x). I'd appreciate feedback so that I know if this is going into the right direction. Thanks!

**Comment by ysb33r** [comment]
@manuelprinz Please see the development-2.0 branch and contirbute any PRs there if yuo want. I am going to close this for now.
