### ISSUE TITLE
Allow verbose mode to be programmatically changed

### ISSUE THREAD

**Issue by eriwen** [asciidoctor/asciidoctor-gradle-plugin#233]
As an asciidoctor Gradle user, I would like to enable verbose mode so that I am notified of broken intra-document links, among other things.

## Expected behavior
Something like this should allow verbose output, perhaps:

```
asciidoctor {
   verbose(true)
}
```

## Context
This will save my and others' time building our own anchor verification tools.

**Comment by mojavelinux** [comment]
I agree. We need to figure out the best way to enable this. This may be something we need to push up into AsciidoctorJ.

As a workaround, you can create the following one-line script named verbose-mode.rb:

```rb
$VERBOSE = true
```

then require it into the runtime using the `requires` option.

```
requires file('verbose-mode.rb')
```

**Comment by mojavelinux** [comment]
@abelsromero @robertpanzer this is related to the logging improvements, but as I've realized in core, verbose mode is orthogonal to the logging severity level.

**Comment by eriwen** [comment]
Thank you for the workaround @mojavelinux. I wasn't sure if asciidoctorj had this capability, so I did not file an issue there, but I knew one would have to add to the asciidoctor extension to make this happen.

**Comment by ysb33r** [comment]
@mojavelinux Should that not be `requires file('/full/path/toverbose.rb')` ? I just tried it with the file name on it's own and then it fails. Setting GEM_PATH to contain the parent directory of the file did not help either.

**Comment by mojavelinux** [comment]
> OR did you mean asciidoctor.requires project.file('verbose.rb') ?

This one. It's a local file, so whatever you need to do to get Gradle to find it.

**Comment by ysb33r** [comment]
Got it.


Sent from my Samsung device

-------- Original message --------

**Comment by cbeams** [comment]
Thanks @eriwen and @ysb33r and @mojavelinux for the conversation so far. It made it easy for me to get up and running with the `verbose-mode.rb` workaround.

However, once I got it working, I noticed that validation warnings don't show the offending file name:

```
asciidoctor: WARNING: invalid reference: maintainter
asciidoctor: WARNING: invalid reference: roles
```

In a larger document base, this can make finding the source of the invalid reference a bit of a goose chase.

**Comment by mojavelinux** [comment]
This is a feature that comes along with 1.5.7. All the messages now get fed through a logger, which have full context about the file to which the message applies. For the API in AsciidoctorJ, see https://github.com/asciidoctor/asciidoctorj/pull/643

**Comment by ysb33r** [comment]
Since we have a workaround for 1.5.x which will still work with 1.5.7 of AsciidoctorJ and I've already starting addressing this in 2.0.x I'm not going to add an enhancement to the 1.5.x plugin series.

**Comment by ysb33r** [comment]
> This is a feature that comes along with 1.5.7. All the messages now get fed through a logger, which have full context about the file to which the message applies. For the API in AsciidoctorJ, see asciidoctor/asciidoctorj#643

The final code is now available in PR #251 and will be available in 2.0-alpha.3. Full loggin availabel for both Gradle worker implementations and JavaExec.

**Comment by eriwen** [comment]
Nice!

**Comment by ysb33r** [comment]
I was under the impression that we could remove the fix I had in alpha.1 once the new asciidoctorj API was in place. I can always re-add the verbose flag functionality.

**Comment by mojavelinux** [comment]
I've requested for a dedicated issue to be opened in AsciidoctorJ to discuss how to control the $VERBOSE global variable in Ruby from the API.
