### ISSUE TITLE
Leverage Action<T> instead of a Closure<?> for better Kotlin DSL compatibility

### ISSUE THREAD

**Issue by sdeleuze** [asciidoctor/asciidoctor-gradle-plugin#236]
It would be nice to update the plugin in order to leverage `Action<T>` instead of a `Closure<?>` for better Kotlin DSL compatibility. I guess that can also help on Groovy DSL side.

**Comment by ysb33r** [comment]
That would be nice, but putting everything in the single README.adoc is getting out of hand. I need to discuss with @mjoavelinux a better way forward.

**Comment by ysb33r** [comment]
I will look into fixing this on the 2.0.x branch

**Comment by ysb33r** [comment]
@sdeleuze Would you be willing to contribute to the development of 2.0? It would be nice for someone to create equivalent `build.gradle.kts` files for some of the `build.gradle` files in the compatibility tests. Then it becomes easier to flush out issues with the Kotlin DSL.

**Comment by jmfayard** [comment]
> Would you be willing to contribute to the development of 2.0? It would be nice for someone to create equivalent build.gradle.kts files for some of the build.gradle files in the compatibility tests. Then it becomes easier to flush out issues with the Kotlin DSL.

@ysb33r I have experience with the Kotlin DSL and I can take care of this!
On the other hand, I know nothing about your project so I would need you to guide me :)

**Comment by ysb33r** [comment]
@jmfayard The contribution would be greatly appreciated. For a start the easiest is to work off `development-2.0` branch. In the various subprojects there will be `*/src/gradleTest` fodlers which contains full Gradle projects. The easiest it write equivalent `build.gradle.kts` files and drop them alongside the `build.gradle` files. GradleTest will thej automatically also perform a Kotlin DSL test.

The best starting point will be `asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup/build.gradle`.

**Comment by jmfayard** [comment]
Having a look now. 

Questions:

- Can I have both `build.gradle` and `build.gradle.kts` inside `asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup` ? Or should I duplicate the folder `complex-jvm-setup`? 
- Any reason why you are not using 
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.20.2-all.zip` ? 
- Would you like to have your variables defined inside the `buildSrc` instead in a groovy hashmap? I could convert `credentials.gradle` for example

**Comment by ysb33r** [comment]
Due to gradle/kotlin-dsl#1261 we cannot automate any of the code snippets at this point in time.  It should still be possible to write some more build scripts and test them by hand againt 2.0-alpha.5 or better.

**Comment by ysb33r** [comment]
We now have Kotlin DSL working up to Gradle 5.1.1. We are SNAFU'd on 5.2.1 and 5.3 due to gradle/kotlin-dsl/#1353. However, any method that takes a closure as configuration option, now has an equivalent method taking an `Action`.
