### ISSUE TITLE
Release 1.5.7 not referenced anywhere

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-gradle-plugin#241]
Bintray has a 1.5.7 build. But there is no reference of this version anywhere in this project, no tags, no release, no text mention in the `history.adoc` (which is pretty old).

<img width="497" alt="screen shot 2018-06-29 at 13 01 45" src="https://user-images.githubusercontent.com/803621/42089309-d9f49d1e-7b9c-11e8-93df-1ce22643e7a3.png">
<img width="713" alt="screen shot 2018-06-29 at 13 01 38" src="https://user-images.githubusercontent.com/803621/42089310-da0add2c-7b9c-11e8-9d9c-2383d8d16a11.png">
<img width="626" alt="screen shot 2018-06-29 at 13 01 15" src="https://user-images.githubusercontent.com/803621/42089311-da206700-7b9c-11e8-97fd-55360e90b7ef.png">

**Comment by ysb33r** [comment]
Wow. That is strange. Even the source code in development still shows 1.5.6, even though on master it is 1.5.7. Maybe @aalmiray  forgot to update development branch again.

**Comment by ysb33r** [comment]
I have rebased the `development` tree from the 1.5.7 that is on `master`.

I also added a note to HISTORY.adoc that we are no longer maintaining that file until we come up with a better solution.
