### ISSUE TITLE
Docinfo for folders tree

### ISSUE THREAD

**Issue by bostandyksoft** [asciidoctor/asciidoctor-gradle-plugin#266]
Hello, for example i have documents structure, that includes subdirectories:

> asciidoctor
        |- folder1 
        |       |- first.adoc 
        |- folder2 
        |        |- second.adoc 
        |- docinfo.html

I want to customize header for each document of my documentation. Maven plugin did it, but when i have switched to gradle, it didn't it. It works only if i copy docinfo.html to each subfolder, but docinfo is same, so i don't want to do this. Is there some way to apply docinfo for documents tree?

So there is configuration of my plugin:

> asciidoctor {
    backends 'html5'
    sourceDir = file('src/main/asciidoc')
    baseDir = file('src/main/asciidoc')
    outputDir = file('build/generated-docs')
    resources {
        from(sourceDir) {
            exclude '**/*.adoc'
        }
    }
    logDocuments = true
    separateOutputDirs = false
    attributes  'source-highlighter': 'coderay',
            'sourceMap': 'true',
            'icons': 'font',
            'idprefix': '',
            'idseparator': '-',
            'figure-caption': 'Рисунок',
            'toc-title': 'Содержание',
            'table-caption': 'Таблица',
            'note-caption': 'Обратите внимание',
            'important-caption': 'Важно',
            'example-caption': 'Пример',
            'warning-caption': 'Осторожно',
            'nofooter': 'true',
            'linkcss': 'true',
            'webfonts!': 'false',
            'iconfont-remote!': 'false',
            'sectanchors': 'true',
            'linkattrs': 'true',
            'docinfo': 'shared'
}

Best regards. Alexey

**Comment by mojavelinux** [comment]
For the Gradle plugin developers, keep in mind that docinfo is an extension point, so it's possible to implement support for docinfo using any strategy you choose.

**Comment by abelsromero** [comment]
It's been a while since I checked the gradle plugin, but seeing he is setting `baseDir = file('src/main/asciidoc')`, what he asks should work.

**Comment by bostandyksoft** [comment]
Hi. Yes, it works now. It seems, that i forgot to run build again when add baseDir option. Sorry for my mistake. Thank you very much!
