### ISSUE TITLE
Misleading message in 1.5.9.2

### ISSUE THREAD

**Issue by bmuschko** [asciidoctor/asciidoctor-gradle-plugin#270]
This message is somewhat misleading to users:

> Implicit attributes projectdir and rootdir are deprecated and will no longer be set in 2.0. Please migrate your documents to use gradle-projectdir and gradle-rootdir instead.

If I see that in my console output then I'd assume that I am actually using one of those attributes. However, my Asciidoc files are not using the attributes. The task [always renders the message](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/src/main/groovy/org/asciidoctor/gradle/backported/AsciidoctorJavaExec.groovy#L142) independent of attribute usage. There's no way to eliminate the message.

**Comment by ysb33r** [comment]
The fix will be in 1.5.9.3 or 1.5.10 whichever comes first. It will only warn if it thinks the attributes are actually used.

**Comment by ysb33r** [comment]
Fix scheduled in 1.5.10.
