### ISSUE TITLE
Plugin should allow receiving lazy evaluation types aka `Provider`

### ISSUE THREAD

**Issue by bmuschko** [asciidoctor/asciidoctor-gradle-plugin#277]
At the moment it's not possible to configure the plugin in a fashion that allows for lazy evaluation of assigned values. You might be available to work around it with Groovy but there's no way to make it happen without tricks expect maybe `afterEvaluate`.

Example: Passing in `project.version` as attribute if the actual value is calculated later e.g. based on Git versioning information.

This plugin should expose properties of type `Provider` in the extension and the task to enable lazy evaluation.

**Comment by ysb33r** [comment]
There is no proper support for lazy evaluation in 1.5.x. This is unfortunately down to the way it was written. 

In 2.x lazy evaluation is done properly and all attributes are seralised to strings only within the task action. I thought `Provider` was already supported in 2.x. but maybe it is not. I'll add a test case for that and do the necessary adjustments if need be.

**Comment by ysb33r** [comment]
> This plugin should expose properties of type Provider in the extension and the task to enable lazy evaluation.

@bmuschko Why is this required? In 2.0 you should simply be able to do

```groovy
asciidoctor {
    attributes 'foo' : (
        providers.provider(
            /* STICK YOUR CALLABLE IN HERE */
        )
    )
}
```

**Comment by bmuschko** [comment]
> Why is this required?

It would be the more idiomatic way to do it. Instead of inspecting individual elements by type, I'd think the better way is to map the `attributes` field as `Property<Map<String, Object>>`. As a side note: at the moment there's no specific [`MapProperty`](https://github.com/gradle/gradle/issues/6863) type yet.

>  In 2.0 you should simply be able to do

I see this comment quite a lot in the issues. When can users expect a release of the 2.0 version?

**Comment by ysb33r** [comment]
> I see this comment quite a lot in the issues. When can users expect a release of the 2.0 version?

The alpha releases are already available.

Officialy when asciidoctorj 1.6.0 gets released the 2.0 plugin version will follow shortly after.

**Comment by ysb33r** [comment]
> It would be the more idiomatic way to do it. Instead of inspecting individual elements by type, I'd think the better way is to map the attributes field as Property<Map<String, Object>>. As a side note: at the moment there's no specific MapProperty type yet.

This means we'll lose compatibility for 4.0-4.2 where a dsign goal for 2.0 was to be compatible with Gradle 4.0+.

**Comment by bmuschko** [comment]
> This means we'll lose compatibility for 4.0-4.2 where a dsign goal for 2.0 was to be compatible with Gradle 4.0+.

I guess you could use `PropertyState` but I wouldn't recommend it. The type might have gotten removed in 5.0 already.

**Comment by ysb33r** [comment]
Final solution has `asciidoctorAttributeProviders` which functions in a way similar to other argumentProviders in Gradle. Will be in final 2.0 release.
