### ISSUE TITLE
Reckoned version 0.1.0-rc.1 has already been released

### ISSUE THREAD

**Issue by theburhan** [asciidoctor/asciidoctor-gradle-plugin#295]
From a release branch let's say release/6.0.x, I have created a feature branch called as feature/api-post-data and then executed the following command 

`./gradlew clean build reckonTagPush -Preckon.stage=rc`
this has created a tag

> 0.1.0-rc.1

then again from release/6.0.x I have created another feature branch called as
feature/api-delete-data and then executed the following command

`./gradlew clean build reckonTagPush -Preckon.stage=rc`
this has created a tag

> 0.2.0-rc.1

now, I decided to make some changes in feature/api-delete-data and committed them, then I executed again
`./gradlew clean build reckonTagPush -Preckon.stage=rc`

which gives me following error

`FAILURE: Build failed with an exception.
What went wrong:
Could not determine the dependencies of task ':library:compileJava'.
 Could not resolve all dependencies for configuration ':library:compileClasspath'.
    Reckoned version 0.1.0-rc.1 has already been released.`

what am I doing wrong? I was expecting that it will bump up to a new version let's say 
> 0.2.0-rc.2

**Comment by Riggs333** [comment]
I'll assume you wanted to create this issue in the project https://github.com/ajoberstar/reckon, right?

**Comment by theburhan** [comment]
> I'll assume you wanted to create this issue in the project https://github.com/ajoberstar/reckon, right?

You're right.
