### ISSUE TITLE
Migrate full documention to Antora

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#303]
Find a way of building extensive documentation for this plugin using the version of the plugin-under-development. 

    As per conversation with @mojavelinux: We're just starting the process of migrating the Asciidoctor docs to Antora. Look for the repo docs.asciidoctor.org in the org. Asciidoctor.js is participating so far. We can add the Gradle plugin to that list.

See also: #102.

**Comment by mojavelinux** [comment]
The move to Antora got held up a bit by the work on 2.0. Once 2.0 is cut, the documentation will be moved into the master branch of core and the new site will be published. Then, we can start bringing in the other projects. Needless to say, it's been a ton of work.

**Comment by mojavelinux** [comment]
cc: @graphitefriction

**Comment by ysb33r** [comment]
@mojavelinux I have worked out a plan so that we can do the docs with the Gradle plugin and that whenever the Antora site is ready it would just be able to pull.

* To write the documentation for the full plugin suite there will be a `docs` folder off the root of the project.
* In order to build the documentation locally, a Gradle composite build will be used to ensure that the docs are built with the same Gradle version that the docs are referring to.
* Prior to building all of the code sources will be copied from their original locations into a temporary location.
* The copied code sources along with the Asciidoc sources will be pushed to a detached branch. When the plugins are published, these sources will be pushed as well. All that Antora has to do is to always pull from this detached branch. (Easily configured in the playbook).
* An `.asciidoctorconfig` will be generated so that IntelliJ users can get the correct previews.

**Comment by mojavelinux** [comment]
That's definitely consistent with our vision for Antora. If we agree on a standard directory structure (whether in the original source or generated), multiple tools should be able to consume it. It also expands the conversation about what the structure should be (and how it should be made, if necessary).

**Comment by mojavelinux** [comment]
Btw, we're still blocked on adding the site to docs.asciidoctor.org by the migration of the core docs. I'm having a meeting about that today so try to get a plan in place to complete it (now that our writer is back).

**Comment by ysb33r** [comment]
> Btw, we're still blocked on adding the site to docs.asciidoctor.org by the migration of the core docs. I'm having a meeting about that today so try to get a plan in place to complete it (now that our writer is back).

That's fine if you are still blocked. I just want to get a move on with writing the docs as having everything in the single README does not scale.

**Comment by mojavelinux** [comment]
Totally agree. There's no reason to hold up on writing and organizing the content. The key goal of the move to Antora is to get us away from the monolithic README so that the documentation is sustainable and maintainable.

**Comment by ysb33r** [comment]
Progress have been made. I have some core infrastructure in place. Now checking that it can actually push documentation to orphaned branches so that gh-pages can now & Antora eventually pick it up.

**Comment by ysb33r** [comment]
Infrastcture implemented so closing this. When the new site becomes available final changes can be tracked via #433

**Comment by mojavelinux** [comment]
You could go ahead and test it now using this playbook.

https://github.com/asciidoctor/docs.asciidoctor.org/blob/master/antora-playbook.yml

I'm fine with adding that to docs.asciidoctor.org since it's not yet live.
