### ISSUE TITLE
Add a Deck.JS plugin

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#306]
Similar to the support we now have for Reveal.JS add a plugin, task types and possibly an extension for Deck.JS (https://github.com/asciidoctor/asciidoctor-deck.js)

**Comment by mojavelinux** [comment]
I don't want to encourage the use of deck.js. We should be pushing users towards reveal.js (probably the best choice for most) or bespoke.

**Comment by ysb33r** [comment]
OK. WIll not fix.
