### ISSUE TITLE
Add support for bundled latex

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#309]
https://github.com/asciidoctor/asciidoctor-latex

**Comment by mojavelinux** [comment]
I'm not sure that's the right move. That extension is mostly unmaintained at this point, and I still feel like a leaner version needs to be split out from it that just provides LaTeX output and no more. The current extension is more like latex-plus. We've discussed and agreed that's what needs to happen, so it's just a matter of doing it.

**Comment by ysb33r** [comment]
OK. When that happens we'll revisit that opportunity again. Closing this issue.
