### ISSUE TITLE
Review the project README after move to Asciidoctor 2.0

### ISSUE THREAD

**Issue by dcp65** [asciidoctor/asciidoctor-gradle-plugin#323]
I'd like to upgrade to version 2.0 of asciidoctor-gradle-plugin (from 1.5.6) but I'm totally confused by the README in its current state. 

Please review and edit.

**Comment by ysb33r** [comment]
What do you find confusing? The upgrade instructions?

**Comment by dcp65** [comment]
Yes. I can't get the upgrade to work even on a very simple project. 

Also, it says upfront that the project is in 'alpha'. But I guess it isn't any more. 

Sorry, I know you guys have done a ton of work on this, but generally I find the readme very long and confusing. Perhaps I should just wait until the 2.0 doc is fully up and running on Antora. 

Here's my `build.gradle`:

```
plugins {
    id 'org.asciidoctor.jvm.convert' version '2.0.0'
}

repositories { jcenter() }

apply plugin: 'org.asciidoctor.jvm.convert'

asciidoctor {
    sourceDir = file("src/docs/asciidoc/")
    ant.touch(file:"${sourceDir}/index.adoc")
    sources {
        include 'index.adoc'
    }
    resources {
        from(sourceDir) {
            include 'images/**'
        }
        from(sourceDir) {
            include 'assets/js/**'
        }
    }
    outputDir "${project.buildDir}"
    attributes = [
            'doctype'      : 'article',
            'toc'          : 'left',
            'sectanchors'   : 'true',
            'toc-title'    :  'My Document',
            'source-highlighter': 'highlightjs',
            'imagesdir'    : './images',
            'docinfo1'     : 'true'
    ]
}```

The `index.adoc` has a bunch of includes that reference other AsciiDoc files in the same directory. 
The build can't find them. 

The README refers to an `includedir`, but if I set that the build fails completely.

**Comment by ysb33r** [comment]
Ah, the directories need some additional description.

You can change `baseDir` to point to your source directory - that is one solution, as by default `baseDir` points to the root project directory. There are reasons for that.

The safest solution is top modify all your includes to

```
include::{includedir}/foo.adoc[]
include::{includedir}/subdir/foo.adoc[]
```

In this way Gradle can relocate your sources if necessary (like when you specify `useIntermediateWorkdir()`) and everything will work transparently. By default `includeDir` will be the same as `sourceDir`.

**Comment by dcp65** [comment]
OK, adding `{includedir}` to each include in the `index.adoc` works. However, the `docinfo` attribute seems to be ignored. All my CSS customizations are missing.

**Comment by ysb33r** [comment]
Mmm... I'll go through the tests we have for docinfo and see if we are testing that correctly.

Can you confirm that none of the content you have in you docinfo-*.html is appearing in the output?

**Comment by dcp65** [comment]
Correct. The generated HTML just uses the default AsciiDoc stylesheet.

**Comment by mrotteveel** [comment]
The requirement to add `{includedir}` to resolve includes correctly goes against the behavior of the include directive documented in the [Asciidoctor User Manual, section File resolution](https://asciidoctor.org/docs/user-manual/#include-resolution):

> If the path relative, the processor resolves the path using the following rules:
> 
> -   If the include directive is used in the main (top-level) document, relative paths are resolved relative to the base directory. (The base directory defaults to the directory of the main document and can be overridden from the CLI or API).
>  -   If the include directive is used in a file that has itself been included, the path is resolved relative to the including (i.e., current) file.
> 
> These defaults makes it easy to reason about how the path to the include file is resolved.

It seems that conflicting definitions of the term base directory are used. This change makes me hesitate to upgrade to asciidoctor-gradle-plugin 2.x.

**Comment by dcp65** [comment]
> This change makes me hesitate to upgrade to asciidoctor-gradle-plugin 2.x.

I'm not hesitating. I'd love to upgrade, but the readme is now so confusing, I haven't a clue how to go about it.

**Comment by dcp65** [comment]
> OK, adding `{includedir}` to each include in the `index.adoc` works. However, the `docinfo` attribute seems to be ignored. All my CSS customizations are missing.

Created #368

**Comment by ysb33r** [comment]
@mrotteveel The usage of `includedir` is very specific to many known uses cases of the Gradle plugin and to provide a stable base for includes.It does seem that somepeoplewould prefer the basedir to always point to `sourceDir` or in case of an intermediate working directory, to wherethesource root is located inside that.

If you feel that this behaviour is more natural to your context, we can add functionality to control it via the DSL i.e.

```groovy
asciidoctor {
    baseDir useSourceRoot()
}
```

Please raise an issue for this and it might still make it into 2.2.0.

**Comment by mrotteveel** [comment]
@ysb33r Done: #369

**Comment by ysb33r** [comment]
@dcp65 I am in the process of implementing #303 and part of that is to create a snapshot documentation website. Have a look at https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-2.0/. 

It currently reflects what will be in 2.30, but it is close enough to the 2.2.0 release. It is effectively the original README broken up so that it can read better, but hopefully it is already an improvement.

**Comment by ysb33r** [comment]
Closing this as we managed to create the snapshot documentation. If you find specific issues in the docs, please raise an issue or better still create a PR.
