### ISSUE TITLE
How can I configure the gradle asciidoctor 2.0 plugin to use pygments.rb as higlighter?

### ISSUE THREAD

**Issue by lwolter** [asciidoctor/asciidoctor-gradle-plugin#326]
Unfortunately, I was not able to configure pygments.rb as a highlighter with the gradle asciidoctor plugin. For a small configuration example, I would be grateful. 
With direct call of asciidoctor and assignment as call parameter I use pygments for a long time for the PDF creation.

**Comment by mojavelinux** [comment]
If possible, I would advise that you consider making the switch from Pygments to Rouge. Rouge is designed to be a drop-in replacement for Pygments, and now comes integrated directly in Asciidoctor. The benefit is that it requires no additional gems or system calls.

Having said that, I realize that if it's possible to continue using Pygments with the 2.0 version of the Gradle plugin, that should be documented. If it's not possible, that should be documented as well.

**Comment by ysb33r** [comment]
We never had an example of that in the plugin before. I will investigate whether pygments work.

**Comment by ysb33r** [comment]
The following should work

```groovy
plugins {
  id 'org.asciidoctor.jvm.pdf' version '2.0.0'
  id 'org.asciidoctor.jvm.gems' version '2.0.0'
}

repositories {
    jcenter()
    maven { url 'http://rubygems-proxy.torquebox.org/releases' }
}

dependencies {
  asciidoctorGems 'rubygems:pygments:1.2.1'
}

asciidoctorPdf {
  dependsOn asciidoctorGemsPrepare
  sourceDir 'docs'

  asciidoctorj {
    requires 'pygments'
    attributes 'source-highligter' : 'pygments'
  }
}
```
Sometime Torquebox goes awry and then it is not possible to retrieve GEMs in a maven way when they are not in the Torquebox cache already.

P.S. The reason why we never had a test for this is that it requires python 2.x to be installed. Even if we used a Docker container for the testing it will add quite a bit of time to the existing test run time. (A full build with all the tests are close to 50min atm).

**Comment by ysb33r** [comment]
If you the option to switch to `rouge` then it will simplify

```groovy
plugins {
  id 'org.asciidoctor.jvm.pdf' version '2.0.0'
}

repositories {
    jcenter()
}

asciidoctorPdf {
  sourceDir 'docs'

  asciidoctorj {
    attributes 'source-highlighter' : 'rouge'
  }
}
```

**Comment by ysb33r** [comment]
I have also added an example to the appendix section of the README.

**Comment by lwolter** [comment]
Sorry, unfortunately I get the following error messages:
`Execution failed for task ':asciidoctorGemsPrepare'.
> Could not resolve all files for configuration ':asciidoctorGems'.
   > Could not resolve rubygems:pygments:1.2.1.
     Required by:
         project :
      > Could not resolve rubygems:pygments:1.2.1.
         > Could not get resource 'http://rubygems-proxy.torquebox.org/releases/rubygems/pygments/1.2.1/pygments-1.2.1.pom'.
            > Could not GET 'http://rubygems-proxy.torquebox.org/releases/rubygems/pygments/1.2.1/pygments-1.2.1.pom'. Received status code 500 from server: Internal Server Error
`

**Comment by ysb33r** [comment]
That's an issue with torquebox as far as I am aware. Raised torquebox/rubygems-servlets#18
