### ISSUE TITLE
Planned release of 2.0.0 to jcenter?

### ISSUE THREAD

**Issue by fapdash** [asciidoctor/asciidoctor-gradle-plugin#327]
I've run into the same problem as https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/267 (posted about it [here](https://github.com/asciidoctor/asciidoctorj/issues/787)).
But because I'm using asciidoctor-gradle-plugin in a [Gradle plugin](https://github.com/vogellacompany/com.vogella.gradle.plugins/tree/master/com.vogella.gradle.plugin.asciidoc) I need to [pull it in from JCenter](https://github.com/vogellacompany/com.vogella.gradle.plugins/blob/d712228ae7b7b1eeaf4b2a0f434efeb875d5b923/com.vogella.gradle.plugin.asciidoc/build.gradle#L29), which only have version 1.6.0 right now, so the new `forkOptions` is not available to me.
Do you have a date for the release of 2.0.0 to jcenter?

**Comment by ysb33r** [comment]
We stopped publishing the Gradle plugins to Bintray. They are only on the portal. Is it not possible just to add another maven repository to your build?

**Comment by fapdash** [comment]
Ah, of course. I didn't realize that I could just reference the `gradlePluginPortal()` in the `repositories { }` block.

Working code:
```
repositories {
	gradlePluginPortal()
	jcenter()
    mavenLocal()
}

dependencies {
	compile localGroovy()
	compile 'org.asciidoctor:asciidoctor-gradle-base:2.0.0'
	compile 'org.asciidoctor:asciidoctor-gradle-jvm-epub:2.0.0'
	compile 'org.asciidoctor:asciidoctor-gradle-jvm:2.0.0'
}
```
