### ISSUE TITLE
Copy non-AsciiDoc files even when sourceDocumentName is set

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-gradle-plugin#39]
When not using the sourceDocumentName, the plugin copies all non-AsciiDoc files to the output directory. Setting the sourceDocumentName inadvertently disables this feature. The plugin should only limit which AsciiDoc file is processed, not change the behavior of how non-AsciiDoc files are handled.

**Comment by ADTC** [comment]
Wait, so how do I tell asciidoctor to _not_ copy those files?
