### ISSUE TITLE
Handle multiple language sourcesets

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#392]
Allow a task to handle a sourceset for various languages.

## Where we are today

Consider that we have a standard setup like

```groovy
asciidoctor {
    sourceDir 'src/docs/asciidoc'
    sources {
        include 'index.adoc'
    }
    resources {
        include 'images/**'
    }
    outputDir "${buildDir}/asciidoc"
}
```

This infers a normal layout of

```bash
src/docs/asciidoc/index.adoc
                 /images/*.*
```

The outputs will end up in `build/asciidoc` (assuming a conventional`buildDir`).

## What we want to add

If we now add a DSL keyword such that

```groovy
asciidoctor {
    languages 'en', 'es'
}
```

it will imply that we have an English and a Spanish sourceset and that the file layout will now be
```
src/docs/asciidoc/en/index.adoc
                 /en/images/**
                 /es/index.adoc
                 /es/images/**
```

Outputs will now end up in 
```bash
build/asciidoc/en
              /es
```

We shall need to accommodate the use case where resources could be language specific
```groovy
asciidoctor {
    resources 'en', {
    }
    resources 'es', {
    }
}
```
and this will only copy that specific resources when the specific language is being processed.

## Keeping current behaviour

If the `languages` keyword is not used, the bhevaiour will be exactly as it is today.

## Dealing with multiple backends

For the case of combining backends and languages
```groovy
asciidoctor {
    outputOptions {
        backends 'html', 'docbook'
    }

    languages 'en', 'es'
}
```
the outputs will be
```bash
build/asciidoc/en/html
                 /docbook
              /es/html
                 /docbook
```

## Other things to deal with

- Intermediate work directories

**Comment by mojavelinux** [comment]
Totally agree. Looks good. Languages as a facet is the right way to go.
