### ISSUE TITLE
Incorrect plugin ID for Kotlin DSL example

### ISSUE THREAD

**Issue by Javaru** [asciidoctor/asciidoctor-gradle-plugin#396]
The README shows the following for installation:
```
Gradle DSL: id 'org.asciidoctor.jvm.convert' version '2.2.0'
Kotlin DSL: id("org.asciidoctor.convert") version "2.2.0"
```
While the alternate syntax is expected, the alternate plugin ID is not. I'm assuming that that is a typo for the Kotlin DSL and that it should also be the new ID of `org.asciidoctor.jvm.convert`.

**Comment by ysb33r** [comment]
Would you fancy just doing providing a quick PR for that?

**Comment by ysb33r** [comment]
Fixed. See http://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#_quick_start
