### ISSUE TITLE
Starting from 1.5.0-alpha.14 (PDF), not compatible with asciidoctor-gradle-plugin

### ISSUE THREAD

**Issue by xlijun** [asciidoctor/asciidoctor-gradle-plugin#399]
1.5.0-alpha.11 works fine. starting from 1.5.0-alpha.14, gradle fails with:

Unable to load class 'org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor'.

I've tried asciidoctor-gradle-plugin 1.5.3 and 1.5.7, the results holds.

**Comment by ysb33r** [comment]
Please see the conversation in 

- #403 
- spring-projects/spring-restdocs#581

The fix to your problem is available in 2.0.4-SNAPSHOT.
