### ISSUE TITLE
[Regression] "invalid reference to unknown anchor" for cross-chapter links in EPUB3

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-gradle-plugin#408]
Please, see [testcase project](https://github.com/slonopotamus/asciidoc-epub3-link-regression). It contains a trivial asciidoctor EPUB setup with two chapters where first chapter has a link to the section in the second chapter in the `<<_chapter2.adoc#subtitle,Link to subtitle in chapter 2>>` form. It uses asciidoctor-gradle-plugin version 3.0.0-alpha.3 with  asciidoctorj-epub3 version 1.5.0-alpha.9.

Way to reproduce:

`./gradlew asciidoctorEpub`

Expected: Gradle happily generates `build/docs/asciidocEpub/asciidoc-test.epub` with two chapters where first chapter has a link to subsection of the second chapter.

Actual: while EPUB does generate (and link properly works), asciidoctor produces a warning:

```asciidoctor: WARNING: _chapter1.adoc: invalid reference to unknown anchor in _chapter2 chapter: subtitle```

Bug does *not* reproduce if I downgrade to asciidoctor-gradle-plugin version 2.2.0 while still using asciidoctor-epub3 version 1.5.0-alpha.9, so I am not sure what part of asciidoc is to blame for this.

**Comment by ysb33r** [comment]
Essentially the Epub code is the same for 2.x and 3.x.

My initial guess is that this is due to a difference between AsciidoctoJ 1.6 and AciidoctorJ 2.0

**Comment by mojavelinux** [comment]
I would suggest testing this with asciidoctor-epub3 directly first to see whether this is even a Gradle plugin issue.

**Comment by ysb33r** [comment]
Couple of points of interest:

- That warning is raised from https://github.com/asciidoctor/asciidoctor-epub3/blob/3fcfb3ee7b74fc1a07c3a91e048717ccb2dd5719/lib/asciidoctor-epub3/converter.rb#L703
- That will only happen if ` refdoc = doc.references[:spine_items].find {|it| refdoc_id == (it.id || (it.attr 'docname')) }` fails to find something.
- If this behaviour is in Ascdiidoctor 2, what would have changed? If it AsciidoctorJ 2.0 it would even be more strange.
- Also I cannot detect that warning via the LogHandler in AsciidoctorJ. So the call to `warn` in the code base is not going the way normal log warnings are going in core.

**Comment by mojavelinux** [comment]
> Also I cannot detect that warning via the LogHandler in AsciidoctorJ. So the call to warn in the code base is not going the way normal log warnings are going in core.

That's correct. Asciidoctor EPUB3 does not yet have the logging integration / shim like Asciidoctor PDF.

**Comment by slonopotamus** [comment]
Correction: the warning this testcase produces is https://github.com/asciidoctor/asciidoctor-epub3/blob/3fcfb3ee7b74fc1a07c3a91e048717ccb2dd5719/lib/asciidoctor-epub3/converter.rb#L700

**Comment by ysb33r** [comment]
Just reproduced this problem using the latest Asciidoctor Docker image. This is not an AsciidoctorJ or Gradle issue.

**Comment by ysb33r** [comment]
Just did with the latest Asciidoctor Docker image and I can reproduce the issue there, so it is definitely not an AsciidoctorJ or Gradle issue.

**Comment by ysb33r** [comment]
> Just reproduced this problem using the latest Asciidoctor Docker image. This is not an AsciidoctorJ or Gradle issue.

After manipulating the docker image to ensure there is not Asciidoctor 2.0 present, I can also say that when doing the same with Asciidoctor (Ruby) 1.5.8 and EPUB 1.5.0-alpha.9 the problem does not occur.

**Comment by ysb33r** [comment]
Just used (newly released) AsciidoctorJ 2.1.0 and the problem goes away.

**Comment by ysb33r** [comment]
@slonopotamus In your asciidoctor-gradle-3.x build, If you set asciidoctorj.version = '2.10' I believe it should work for you.

**Comment by slonopotamus** [comment]
@ysb33r 
1. You wanted to say '2.1.0' instead of '2.10'. I believe this versioning thing will bring a lot of confusion if asciidoctor-2.1.0 is released ;)
2. asciidoctorj-2.1.0 still isn't available in jcenter even though it was released ~4h ago. Waiting.

**Comment by ysb33r** [comment]
Yup, I meant 2.1.0

**Comment by slonopotamus** [comment]
asciidoctorj-2.1.0 is kinda SNAFU. See asciidoctor/asciidoctorj#829.

**Comment by slonopotamus** [comment]
Ok, I've [updated](https://github.com/slonopotamus/asciidoc-epub3-link-regression/commit/088a8c5367089a09968c0412b70f391a7d4bd16d) asciidoctorj to 2.1.0 in test project, but the warning is **not** fixed.

**Comment by ysb33r** [comment]
OK. I better look into that, because my test was passing. Maybe I should clean my local build cache.

**Comment by ysb33r** [comment]
> OK. I better look into that, because my test was passing. Maybe I should clean my local build cache.

Yup @slonopotamus, you're right about the warning still being there.

**Comment by ysb33r** [comment]
@mojavelinux Can you move this issue to asciidoctor-epub3, please? I think we have enough proof that this is neither asciidoctorj or asciidoctor-gradle issue.

**Comment by slonopotamus** [comment]
Closing issue, everyone agreed that it is not asciidoctor-gradle-plugin fault.

**Comment by mojavelinux** [comment]
This will be fixed in asciidoctor-epub3 alpha.10.
