### ISSUE TITLE
Project description still links to old 1.5.x doc

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-gradle-plugin#444]
This project description, still links to the 1.5.x documentation, which is a bit misleading and confusing.

> A Gradle plugin that uses Asciidoctor via JRuby to process AsciiDoc source files within the project. http://asciidoctor.org/docs/asciidoctor-gradle-plugin

The description should be updated to the [new documentation link](https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-2.0) even if it's temporary, it is aligned with the current 2.x releases.

**Comment by ysb33r** [comment]
Will now point to the intermediate pages site until Antora website is up and running
