### ISSUE TITLE
Make AsciidoctorTask cacheable

### ISSUE THREAD

**Issue by lacasseio** [asciidoctor/asciidoctor-gradle-plugin#448]
I want to reopen the discussion around https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/215 as it makes no sense for Gradle to keep a [implementation of a cacheable task in our own codebase](https://github.com/gradle/gradle/blob/f0caecfaab36a7db60e0ba1b9d532e4909babf5c/buildSrc/subprojects/build/src/main/groovy/org/gradle/build/docs/CacheableAsciidoctorTask.groovy).

The first question would be is this something the `asciidoctor-gradle-plugin` team want to make part of the next release? A follow-up question would be is backward compatibility against Gradle 2.0 still a concern?

**Comment by lptr** [comment]
PR https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/449 should fix this.

**Comment by ysb33r** [comment]
Will be in 2.4.0 release.
