### ISSUE TITLE
task asciidoctorPdf will generate a PDF file with unprocessed diagram

### ISSUE THREAD

**Issue by ixchelruiz** [asciidoctor/asciidoctor-gradle-plugin#450]
gw asciidoc will generate a PDF file with a **correct** ditaa diagram 
gw asciidocPdf will generate a PDF file with a **incorrect** ditaa diagram 

Example project that reproduces the error:
https://github.com/ixchelruiz/asciidoctor-gradle-diagram

![asciidocPdf](https://user-images.githubusercontent.com/1284934/66223953-0783a000-e6d5-11e9-97c5-37fb73d1c035.jpg)
[asciidocPdf-index.pdf](https://github.com/asciidoctor/asciidoctor-gradle-plugin/files/3691467/asciidocPdf-index.pdf)
[asciidoc-index.pdf](https://github.com/asciidoctor/asciidoctor-gradle-plugin/files/3691468/asciidoc-index.pdf)

**Comment by msgilligan** [comment]
@ixchelruiz Why did you close this issue? I think I'm seeing the same problem.
