### ISSUE TITLE
`AbstractAsciidoctorTask#asConfiguration` not doing what it's supposed to

### ISSUE THREAD

**Issue by lacasseio** [asciidoctor/asciidoctor-gradle-plugin#460]
You can spot the bug here: https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L1135-L1144

It should be `switch (sourceConfig.class)` do the type is compared inside the switch. Else it just always goes to the default case.

**Comment by lacasseio** [comment]
It seems there is the same bug here: https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L1124-L1133

**Comment by ysb33r** [comment]
This will be in 2.4.0 and 3.0.0-alpha.4
