### ISSUE TITLE
PDF task's defaults may override user-provided configuration

### ISSUE THREAD

**Issue by wilkinsona** [asciidoctor/asciidoctor-gradle-plugin#478]
The defaults are set on the PDF task using an `Action`:

https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/a4507c00eb50d2e807f89105acab788ebf97a002/asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJPdfPlugin.groovy#L46-L57

In certain circumstances, this `Action` may be called after a user-provided action. The end result is that the defaults take precedence over the user's own configuration. This is illustrated by this [minimal example](https://github.com/asciidoctor/asciidoctor-gradle-plugin/files/3969025/asciidoctor-pdf-defaults-problem.zip). A `buildSrc` plugin sets the `sourceDir` of all `AbstractAsciidoctorTask`s to `src/docs/custom`. This works fine for `AsciidoctorTask` but does not work for `AsciidoctorPdfTask`. The former finds and processes the source in the custom location, the latter believes that it has no source:

```
$ ./gradlew clean asciidoctor asciidoctorPdf --console=plain
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
:asciidoctor /Users/awilkinson/dev/temp/asciidoctor-pdf-defaults-problem/src/docs/custom
:asciidoctorPdf /Users/awilkinson/dev/temp/asciidoctor-pdf-defaults-problem/src/docs/custom

> Task :clean
> Task :asciidoctor
> Task :asciidoctorPdf NO-SOURCE

BUILD SUCCESSFUL in 6s
2 actionable tasks: 2 executed
```

A, somewhat brittle, workaround is to change the order in which the plugins are applied:

```
plugins {
	id 'org.asciidoctor.jvm.convert'
	id 'org.asciidoctor.jvm.pdf'
	id 'com.example'
}
```

**Comment by ysb33r** [comment]
Looks like a bug, because order of plugins should not be a factor.

**Comment by ysb33r** [comment]
Will be in 3.0.0 final.
