### ISSUE TITLE
torquebox proxy is down, apparently forever

### ISSUE THREAD

**Issue by jnizet** [asciidoctor/asciidoctor-gradle-plugin#483]
See https://github.com/torquebox/rubygems-servlets/issues/20#issuecomment-567602752:

> Because I don't have time to work out the issues that cause it periodic downtime (TL;DR running out of storage space) nor do I have time to get it properly setup with TLS certs, I've decided to pull the proxy itself down to flush out any remaining usage and get those changed.

> You're right the actual server is up again - it just won't serve any more artifacts.

I'm using version 2.4.0 of the org.asciidoctor.jvm.revealjs gradle plugin, and the documentation advises to use this proxy. Is there any alternative, even temporary?
Even downloading the gem dependencies manually and storing them in the repo would be fine, but having absolutely no knowledge of the ruby/jruby ecosystem, I don't even know how to do that.

**Comment by mojavelinux** [comment]
According the the JRuby base plugin:

> As of version 1.1.0, the JRuby/Gradle base plugin supports embedding a rubygems-servlets process inside the Gradle process itself. This obviates the need for a third-party proxy to present the Maven-compatible dependency information that JRuby/Gradle relies on.

See http://jruby-gradle.org/base/

So, apparently, yes.

**Comment by ysb33r** [comment]
The old one never worked properly, but there is a rewritten one now in 2.0.0-alpha.3 of the JRuby plugin. This will shortly be integrated into the 3.x series. (At this point I am not sure how much effort the backport to 2.x will be, but I know it will be far from trivial).

**Comment by ysb33r** [comment]
> I'm using version 2.4.0 of the org.asciidoctor.jvm.revealjs gradle plugin, and the documentation advises to use this proxy. Is there any alternative, even temporary?
Even downloading the gem dependencies manually and storing them in the repo would be fine, but having absolutely no knowledge of the ruby/jruby ecosystem, I don't even know how to do that.

@jnizet If you download them manually and put all the GEMs in a directory you can use Gradle's `flatDir` repo.

**Comment by jnizet** [comment]
@ysb33r thanks a lot for your suggestion. That would be fine for now. The thing is, I have no idea of where to find the jars to download, since the proxy which served them is now down. I see that my build directory, created from previous builds, has an `asciidoctorGems` directory, which contains the following (I stopped the tree at level 2)

```
asciidoctorGems
├── bin
│   └── asciidoctor-revealjs
├── build_info
├── cache
│   ├── asciidoctor-revealjs-2.0.0.gem
│   ├── concurrent-ruby-1.1.5.gem
│   └── thread_safe-0.3.6-java.gem
├── doc
├── extensions
├── gems
│   ├── asciidoctor-revealjs-2.0.0
│   ├── concurrent-ruby-1.1.5
│   └── thread_safe-0.3.6-java
└── specifications
    ├── asciidoctor-revealjs-2.0.0.gemspec
    ├── concurrent-ruby-1.1.5.gemspec
    └── thread_safe-0.3.6-java.gemspec
```

So maybe I could be able to recreate the jars from there, but I have no idea of what the jar should contain, given by complete ignorance of the ruby/jruby ecosystem.

**Comment by Mogztter** [comment]
Did you try the following?

```
repositories {
  flatDir '/somewhere/asciidoctorGems'
}
```

Or maybe:
```
repositories {
  flatDir '/somewhere/asciidoctorGems/gems'
}
```

Also Dan documented how to use a gem from git without the dependency management part: https://github.com/asciidoctor/asciidoctor-pdf/issues/650#issuecomment-258338060

You can download `.gem` files directly from https://rubygems.org/. For instance: https://rubygems.org/downloads/rouge-3.14.0.gem

**Comment by jnizet** [comment]
Thanks @Mogztter. I dd try the two flatDirs options. I also try following the explanations you linked to, but without any success (and without understanding how it should be applied to my case).

To be honest, I feel completely lost, and I have no idea of what I could do, except waiting for a version of the org.asciidoctor.jvm.revealjs gradle plugin that doesn't depend on the abandoned proxy anymore, or for a complete tested example showing how to use the plugin without relying on the proxy.

**Comment by ysb33r** [comment]
I am trying to get a version, out but it is blocked by a hang up issue in dependency resolution.

**Comment by Mogztter** [comment]
@robertpanzer found a solution to workaround this issue. I'm using version 2.4.0 of the Asciidoctor Gradle plugin and it's working great.

1. Add `com.github.jruby-gradle.base` plugin version 1.7.0 into your `plugins`:

```gradle
plugins {
  id 'com.github.jruby-gradle.base' version '1.7.0'
}
```

2. Disable the default repository:

```gradle
jruby {
  defaultRepositories false
}
```

3. Enable `rubygems` in your `repositories`:
```
repositories {
  mavenCentral()
  jcenter()
  rubygems('https://rubygems.org')
}
```

That's all!

For reference, I'm using the following dependency to enable the Rouge syntax highlighter in Asciidoctor:

```gradle
dependencies {
  asciidoctorGems 'rubygems:rouge:3.13.0'
}
```

If your configuration is correct, you should see some logs about jetty: 

```console
$ ./gradlew asciidoctorRevealJs

> Configure project :
2019-12-22 23:05:30.446:INFO::Daemon worker Thread 3: Logging initialized @4283963ms

> Task :asciidoctorGemsPrepare
2019-12-22 23:05:30.569:INFO:oejs.Server:Execution worker for ':': jetty-9.2.12.v20150709
2019-12-22 23:05:35.158:INFO:oejs.ServerConnector:Execution worker for ':': Started ServerConnector@2ad0f0f3{HTTP/1.1}{localhost:42685}
2019-12-22 23:05:35.159:INFO:oejs.Server:Execution worker for ':': Started @4288676ms

> Task :asciidoctorGemsPrepare UP-TO-DATE
2019-12-22 23:05:35.967:INFO:oejs.ServerConnector:Daemon worker Thread 3: Stopped ServerConnector@2ad0f0f3{HTTP/1.1}{localhost:0}

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
2 actionable tasks: 2 up-to-date
```

The reason is that the JRuby Gradle plugin will boot an embedded jetty server with the proxy servlet that directly connects to rubygems.org.

ping @jnizet

**Comment by jnizet** [comment]
Thanks a lot @Mogztter. This works! 

I've been unable to translate this to the Gradle Kotlin DSL syntax though: I have no idea of how to translate `rubygems('https://rubygems.org')`

**Comment by ysb33r** [comment]
@jnizet 3.0.0-alpha.4 will address this. I have prepared all of the changes. When @aalmiray has the time he will release it.

Post release you will only need to do 
```
repositories {
  mavenCentral()
  jcenter()
  ruby.gems()
}
```
