### ISSUE TITLE
Resources should be copied prior to execution

### ISSUE THREAD

**Issue by marcphilipp** [asciidoctor/asciidoctor-gradle-plugin#493]
We've been following [@mojavelinux' recommendation](https://github.com/asciidoctor/asciidoctor-pdf/issues/271#issuecomment-291992364) to include both static and generated (using asciidoctor-diagram) images in the PDF version of the JUnit 5 User Guide.

I've now tried to migrate from the old `org.asciidoctor.convert` plugin to the new `org.asciidoctor.jvm.convert` one. The current status quo can be seen on a [branch in the junit5 repo](https://github.com/junit-team/junit5/tree/asciidoctor-plugin-2.4.0). However, running asciidoctor-pdf produces the following warnings and consequently fails to include the referenced images:

> WARNING: image to embed not found or not readable: documentation/build/docs/asciidoc/user-guide/images/writing-tests_execution_mode.svg

The image files are there after the task finishes, though. From a brief look at the code, it looks like the old task copied the resources to the destination directory prior to execution while the new one does it the other way around. Is there a reason why this was changed? Is it possible to change it back to the way it was before? In the meantime, I'd appreciate workaround ideas.

**Comment by ysb33r** [comment]
Use the org.asciidoctor.jvm.pdf plugin instead. It is more optimised for PDF generation.

**Comment by marcphilipp** [comment]
I tried that and it has the same issue.

**Comment by marcphilipp** [comment]
I found a rather ugly workaround: https://github.com/junit-team/junit5/blob/63e92849154d91bb1f9237b824b3e900a6c76a29/documentation/documentation.gradle.kts#L190-L202

**Comment by ysb33r** [comment]
Ah I see and that IS a ugly workaround.

I remember there was a reason why copying resources was moved to the end and I suspect it had to do with the way that we had to adjust dealing with optimising the backends as well as dealing with multi-language conversions.

Since you are using asciidoctor-diagram which are missing, I assume it is your static diagrams that are missing?

**Comment by ysb33r** [comment]
Oh and @marcphilipp try using `asciidoctorPdf.useIntermediateWorkDir()`. If that does not work, then I'll have to find a way to fix this issue.

**Comment by lhotari** [comment]
I wonder if using `baseDirFollowsSourceFile()` introduced in #492 would fix the issue?

**Comment by marcphilipp** [comment]
I tried both but couldn't get it to work. 😞 

Here's a minimal project that reproduces the issue:
https://github.com/marcphilipp/asciidoctor-gradle-plugin-issue-493

To reproduce, run `./gradlew --rerun-tasks cleanAsciidoctorPdf asciidoctorPdf

Could you give it a try, please?

**Comment by rwinch** [comment]
I am also experiencing this problem, but with the html5 backend and external css. See https://github.com/rwinch/asciidoctor-gradle-resource-failure

**Comment by ysb33r** [comment]
@rwinch @marcphilipp Will be in the 3.1.0 release. Hopefully this switchover will not cause problem for others. If it does we'll just make this behaviour configurable in a future release

**Comment by marcphilipp** [comment]
@ysb33r Thanks! 👍
