### ISSUE TITLE
revealjsOptions.slideNumber can be a string

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-gradle-plugin#500]
See: https://github.com/asciidoctor/asciidoctor-reveal.js/pull/239/files

> Display the page number of the current slide.
> *true* will display the slide number with default formatting.
> Additional formatting is available:
> h.v: horizontal . vertical slide number (default)
> h/v: horizontal / vertical slide number
> c: flattened slide number
> c/t: flattened slide number / total slides

**Comment by ysb33r** [comment]
@Mogztter Fancy adding that support on the development-3.x branch?

**Comment by Mogztter** [comment]
Out of curiosity, what is the purpose of the master branch? Is there a planned 4.x version?

> Fancy adding that support

I'm gonna try :wink:

**Comment by ysb33r** [comment]
What is the `development-3.x` branch will become `master`, but currently `master` is still the mainstream 2.x releases.

**Comment by ysb33r** [comment]
Will be in 3.0.0 final.
