### ISSUE TITLE
Configure ArtifactRepository that Only Operate on Asciidoctor Gradle Configurations

### ISSUE THREAD

**Issue by rwinch** [asciidoctor/asciidoctor-gradle-plugin#511]
I'd like to be able to specify a Gradle [ArtifactRepository](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/ArtifactRepository.html) that only operates on the `Configurations` used by the Asciidoctor Gradle Plugin's dependencies. The reason for this is that I'd like to use a different repository for Gradle Asciidoctor dependency resolution vs the rest of the project.

**NOTE**: I do not want to maintain a list of allowed artifacts as anything in the configuration should be allowed.

Gradle allows doing this by configuration name using [ArtifactRepository.content](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/ArtifactRepository.html#content-org.gradle.api.Action-) method. An example of what that would look like can be seen below:

```java
project.getRepositories().maven(repo -> {
	repo.setUrl(URI.create("https://jcenter.bintray.com/"));
	repo.mavenContent(descriptor -> {
		descriptor.onlyForConfigurations("asciidoctor",....);
	});
});
```

Unfortunately, `AsciidoctorJExtension` currently [creates a detached configuration](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/6382611322e68fae23ec7273bc6dde8a04bdfeff/jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy#L604) which means there is no way for me to refer to it by name.

Can something be modified so that I can configure a repository that only resolves the Asciidoctor Gradle Plugin dependencies without the need to maintain a list of allowed artifacts?

**Comment by ysb33r** [comment]
Wow, interesting feature! Quite a bit niche too.

What about we provide a `AsciidoctorJExtension.configurationCallback(Action<Configuration> cfg)` method? Then I reckon you should be able to create an Action and just pass it.
```java
MavenArtifactRepository repo; // from somewhere
Action abc = new Action<Configuration> () {
            @Override
            void execute(Configuration cfg) {
               repo.mavenContent( descriptor -> { descriptor.onlyForConfigurations(cfg.getName());  } )
            }
        }

// And then somewhere
asciidoctorj.configurationCallback(abc);
```

**Comment by rwinch** [comment]
Thank you for the response @ysb33r! I think that would work nicely.

**Comment by ysb33r** [comment]
Will be in 3.1.0.
