### ISSUE TITLE
Add an option to disable 'useIntermediateWorkdir'

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-gradle-plugin#524]
Currently, AsciidoctorEpubTask [unconditionally enables 'useIntermediateWorkdir'](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy#L68). Even when the issue this was added for (asciidoctor/asciidoctor-epub3#190) is fixed (this is going to happen in the nearest week or two), user will not be to avoid intermediate workdir because there's no method to disable it.

Combined with the fact that `useIntermediateWorkdir` doesn't Just Work (#523), this all makes things even worse than they would be if `useIntermediateWorkdir` workaround wasn't added to `AsciidoctorEpubTask` at all.

**Comment by ysb33r** [comment]
As soon as you have asciidoctor/asciidoctor-epub3#190 fixed, would you create a PR with the new epub version and that line removed?

**Comment by slonopotamus** [comment]
OK

**Comment by slonopotamus** [comment]
See #533.
