### ISSUE TITLE
Run asciidoctor-epub3 in-process

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-gradle-plugin#534]
The only reason why a forked JVM is spawned to run asciidoctor-epub3 I know is passing path to Kindlegen executable. But, since asciidoctor/asciidoctor-epub3#277 (already available in current asciudoctor-epub3 release that you use), it is possible to pass path through `ebook-kindlegen-path` document attribute, so it looks like there's no more need to fork.

If you encounter any issues implementing this, feel free to bugreport them to asciidoctor-epub3 project.

**Comment by ysb33r** [comment]
Feel free to make the relevant change and push it. If the test all pass then we are good.

**Comment by ysb33r** [comment]
This will run in process from Gradle 6.0+. In previous versions it will still be run out of process as Gradle leaks snakeyaml onto the classpath.
