### ISSUE TITLE
Add an option to configure the failure level and fail the task accordingly

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-gradle-plugin#536]
Asciidoctor can return a non-zero exit code if specified logging level is reached. For instance, it can be useful when you want to fail if an include directive is not found (by setting `failure_level` to `WARN`).

In the context of Gradle, I think we should probably throw an exception to fail the task.

I can submit a pull request with a few guidance on how to (properly) fail task.

**Comment by ysb33r** [comment]
Closed. Will be in 3.2.0

**Comment by abelsromero** [comment]
Trying to test this I see this only works in tasks with 

```
asciidoctor {
    failureLevel 'ERROR'
}
```

But `failureLevel` is not valid in the extension

```
asciidoctorj {
}
``` 

Is that intended?

**Comment by ysb33r** [comment]
```
asciidoctor {
  asciidoctorj {
    failureLevel 'ERROR'
 {
}
```
