### ISSUE TITLE
Images not appearing in hmtl but in pdf

### ISSUE THREAD

**Issue by pirancaci** [asciidoctor/asciidoctor-gradle-plugin#539]
Hi. I have configured `build.gradle` that way to use asciidoctor task. I want to produce html and pdf files from the asciidoc files from committing the same task 'asciidoctor'. I have been able to produce everything except of images in html. For some reason the images are not able to te be shown in the hmtl converted files in the `build/docs/asciidoc` but surprisingly they are being shown in the pdf converted files, so I assume there is not a big problem in my configuration. Still I can't find where my Problem is. I found out that the images folder its not being copied into the `buildDir` together with the hrml files for some reason. I would be happy if somebody could help me :D

The following is my `build.gradle` file:

```gradle
buildscript {
   repositories {
       maven {
         url "https://plugins.gradle.org/m2/"
         }
   }
   dependencies {
        //asciidoctor gradle plugin
        classpath "org.asciidoctor:asciidoctor-gradle-jvm:3.1.0"
        //pdf plugin
        classpath "org.asciidoctor:asciidoctor-gradle-jvm-pdf:3.1.0"
        //gems plugin for diagrams
        classpath "org.asciidoctor:asciidoctor-gradle-jvm-gems:3.1.0"
        //plugin for diagram with rubygems() repository
        classpath "com.github.jruby-gradle:jruby-gradle-plugin:2.0.0"
   }
}

apply plugin: 'java'
//asciidoctor gradle plugin
apply plugin: "org.asciidoctor.jvm.convert"
//pdf plugin
apply plugin: "org.asciidoctor.jvm.pdf"
//gems plugin
apply plugin: "org.asciidoctor.jvm.gems"
//jruby
apply plugin: "com.github.jruby-gradle.base" 

repositories {
        jcenter()
        maven { url 'http://rubygems-proxy.torquebox.org/releases' }
        
    }

dependencies{
   asciidoctorGems 'rubygems:asciidoctor-diagram:2.0.1'
}

asciidoctorj{
   
   requires = ['asciidoctor-diagram']
   
}

asciidoctor{
   
   sourceDir  file('src/main/java') 
   
   dependsOn asciidoctorGemsPrepare
   
   baseDirFollowsSourceFile()
   
   
   attributes \
   'build-gradle': file('build.gradle'),
   'sourcedir': project.sourceSets.main.java.srcDirs[0],
   'source-highlighter': 'coderay',
   'endpoint-url': 'http://example.org',
   'imagesdir': 'images',
   'toc': 'right',
   'icons': 'font',
   'setanchors': '',
   'idseparator': '-',
   'idprefix': 'slide-',
   'docinfo': 'shared'
   
  outputOptions{
      backends = ['html5', 'pdf']
      separateOutputDirs = true;
    }  
}
```
<img width="479" alt="pic" src="https://user-images.githubusercontent.com/35587443/76947098-6779a600-6905-11ea-88f4-5d0e8e292b8e.png">

**Comment by Mogztter** [comment]
Please read the user manual: https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#_processing_auxiliary_files

**Comment by pirancaci** [comment]
> Please read the user manual: https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#_processing_auxiliary_files

Thank you :) I solved my problem

**Comment by Mogztter** [comment]
Excellent news 👍
