### ISSUE TITLE
Support generation of asciidoctorconfig files

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#543]
I would like to add an additional plugin which can generate `.asciidoctorconfig` files, which in turn is used by IntelliJ. The plugin itself will not be dependent on asciidoctorj or asciidoctor.js.

When applied the plugin will create a task called `asciidoctorEditorConfig`. It will be configurable as follows:

```groovy
asciidoctorEditorConfig {
  // Specify attribute substitution as a map
  // Attributes from this map will be added first into the generated file.
   attributes gradleVersion : gradle.gradleVersion,
            revnumber: version,
            topdir  : rootDir.absolutePath

    // Read additional attributes from a file (will not be substituted, simply appended)
    additionalAttributes  'src/docs/asciidoc/attributes.adoc'

    // If an existing project or task extension is supplied attributes will be read from there as well
    additionalAttributes asciidoctorj

    // Set the destination directory - will default to the root of the project.
    destinationDir = projectDir
}
```

It will also inject a dependency on the `idea` plugin, such that when an an import into IntelliJ is applied, it will also run this task.

It will be the responsibility of the project owner to add this generated file to `.gitignore`.

See also: https://github.com/asciidoctor/asciidoctor-intellij-plugin

CC: @ahus1

**Comment by ahus1** [comment]
Hi @ysb33r - I'm excited that you like this feature!

Originally this was intended to be committed to the source of the version control system. The way you describe it it will be useful to generate it using Gradle. 

I assume that users will need to add the file to _.gitignore_, as it will be re-created by Gradle? Would it be cleaned by the _clean_ target?

For everyone else reading this thread: you can find out more about .asciidoctorconfig in the wiki space of the AsciiDoc plugin for IntelliJ: https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations

**Comment by ysb33r** [comment]
> I assume that users will need to add the file to .gitignore, as it will be re-created by Gradle?

Yes. 

> Would it be cleaned by the clean target?

I don't believe so, because it does not end up in the `build` directory. I have to check whether `cleanAsciidoctorEditorConfig` will delete it.

**Comment by ysb33r** [comment]
Will be in 3.2.0

**Comment by ahus1** [comment]
I've added a back-link to this feature to the plugin's wiki: https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations#ecosystem

Feel free to update it as necessary.
