### ISSUE TITLE
Without the latest doc for 3.2.0

### ISSUE THREAD

**Issue by mystic-cg** [asciidoctor/asciidoctor-gradle-plugin#548]
I follow this https://asciidoctor.org/docs/user-manual/#gradle, whose version and config are still 1.5.9.2.
Where is the latest doc? 
If you know, please tell me.
Thanks a lot.

**Comment by mojavelinux** [comment]
See #433 to learn what's happening with the docs.

**Comment by mystic-cg** [comment]
Thank you. 
Looking forward to the release of new docs.
