### ISSUE TITLE
pdfTheme documentation wrong?

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-gradle-plugin#563]
I copied the following from the documentation https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#asciidoctorj-pdf-plugin into my script:

```

asciidoctorPdf {
// more stuff
pdfThemes {
    local 'basic', { 
        styleDir = file('themes/basic') 
        styleName = 'very-basic' 
    }
}
}
```
But this results into an error:

* Where:
Build file '/home/vogella/git/content/build.gradle' line: 115

* What went wrong:
A problem occurred evaluating root project 'content'.
> No such property: styleDir for class: org.asciidoctor.gradle.jvm.pdf.AsciidoctorPdfThemesExtension

**Comment by vjlamp** [comment]
Thank you, @ysb33r, for fixing this. Please don't forget to update the published page. I ran into the same issue today because the website still contains the wrong information.
If anyone wondering what the fix is: Use `themeDir` instead of `styleDir` and `themeName` instead of `styleName`.

**Comment by l3nz** [comment]
I was bitten by the same bug - the documentation seems to be wrong. https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#asciidoctorj-pdf-plugin

I googled and found this page.... but it would be better to fix it for good :-)

**Comment by abelsromero** [comment]
Just by chance we started working on fixing docs yesterday :sweat_smile: https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/716 It will be fixed soon :tm:

**Comment by vogella** [comment]
Thanks. Verified that it is fixed in https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide/#asciidoctorj-pdf-plugin
