### ISSUE TITLE
Strip out Kindlegen support

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#576]
Prior to finding an alternative to Kindlegen, we need to strip out existing support as it prevents us from releasing.

**Comment by mojavelinux** [comment]
There is actually an alternative, albeit still very young and experimental. See https://github.com/slonopotamus/dyck (the name is still under debate).

**Comment by ysb33r** [comment]
Yes, but the implementation within the plugin will be quite a bit different. SO it is better to remove the support and then re-add it with the new implemetnaiton in the next release.

**Comment by mojavelinux** [comment]
I definitely agree.
