### ISSUE TITLE
Can't get my include processor extension to work

### ISSUE THREAD

**Issue by edward3h** [asciidoctor/asciidoctor-gradle-plugin#581]
I've been trying to make a custom IncludeProcessor extension, following the instructions at https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide/#_as_project_dependency

My extension doesn't seem to get picked up and I'm stumped as to why.
I made a minimal example at 
https://github.com/edward3h/adoc_extension_test

Can you see what is wrong with it, or else suggest a next step for debugging it?

**Comment by abelsromero** [comment]
I am afraid the docs are not up to date with latest Asciidoctorj changes.
Rename the SPI file `org.asciidoctor.extension.spi.ExtensionRegistry` to  `org.asciidoctor.jruby.extension.spi.ExtensionRegistry` and should work.

**Comment by edward3h** [comment]
Thanks for the quick answer!
