### ISSUE TITLE
Update dependency on org.asciidoctor:asciidoctorj-groovy-dsl to a version resolvable from Maven Central

### ISSUE THREAD

**Issue by erdi** [asciidoctor/asciidoctor-gradle-plugin#596]
The plugin depends on a version of `org.asciidoctor:asciidoctorj-groovy-dsl` which is only resolvable from [JCenter which is being sunsetted](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Unfortunately that dependency is resolved via a detached configuration which means that its version cannot be controlled via a dependency resolve rule. 

There is now [a version available from Maven Central](https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-groovy-dsl), it would probably be good to switch to that.

**Comment by ysb33r** [comment]
Permanently fixed in 4.0.0-alpha.1
