### ISSUE TITLE
[Java 16] FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem

### ISSUE THREAD

**Issue by juergenzimmermann** [asciidoctor/asciidoctor-gradle-plugin#597]
When I invoke `gradle asciidoctor` with Java 16 then I get the output `WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem`.

Using `gradle asciidoctor --info` shows the following detail:

```
[...]
> Task :asciidoctor
Custom actions are attached to task ':asciidoctor'.
Build cache key for task ':asciidoctor' is 2c54f1ebd95b48c40d5bbcde5de0bc39
Copy resources for 'html5' to C:\Users\[...]\IdeaProjects\kunde\build\docs\asciidoc
Running AsciidoctorJ instance with classpath [...]
Starting process 'command 'C:\Zimmermann\jdk\bin\java.exe''. Working directory: C:\Users\[...]\IdeaProjects\kunde Command: C:\Zimmermann\jdk\bin\java.exe -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de -Duser.variant -cp [...] org.asciidoctor.gradle.remote.AsciidoctorJavaExec C:\Users\[...]\IdeaProjects\kunde\build\tmp\asciidoctor.javaexec-data
Successfully started process 'command 'C:\Zimmermann\jdk\bin\java.exe''
2021-04-05T05:09:47.261+02:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
[...]
```

**Comment by alwyn** [comment]
Can confirm this happening.  Trying to find a way to specify jvmargs for the asciidoctor subprocess, but nothing so far.

**Comment by ysb33r** [comment]
Try this
```groovy
asciidoctor {
  inProcess = JAVA_EXEC // or "JAVA_EXEC"
  forkOptions {
     jvmArgs '-Dfoo-base', '-XX:something=more'
  }
}
```

`forkOptions` configures a `org.ysb33r.grolifant.api.JavaForkOptions` which has a similar interface to `org.gradle.process.JavaForkOptions`

**Comment by alwyn** [comment]
@ysb33r Looks promising although it doesn't seem to take the --add-opens argument. 

Trying:
```
    asciidoctor {
        inProcess = JAVA_EXEC
        forkOptions {
            jvmArgs("--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED")
        }
        dependsOn(asciidoctorPdf)
    }
```
with asciidoctorPdf having the same configuration.

I am using some --add-opens on the main gradle process to get `kapt` to work, but for some reason the asciidoctor process complains with:
`Unrecognized option: --add-opens java.base/sun.nio.ch=ALL-UNNAMED`

**Comment by juergenzimmermann** [comment]
The following code fragment works for my `build.gradle.kts` file:

```
inProcess = org.asciidoctor.gradle.base.process.ProcessMode.JAVA_EXEC
forkOptions {
     jvmArgs("--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", "--add-opens", "java.base/java.io=ALL-UNNAMED")
}
```

**Comment by ysb33r** [comment]
@alwyn You need to pass a list, not a single concatenated string.

**Comment by ysb33r** [comment]
@juergenzimmermann Unless Gradle specifically dopes somethign in future releases, it look likes the plugin might have to add those options automatically if it detects JDK16.

**Comment by 9ao9ai9ar** [comment]
[`forkOptions` are marked as deprecated](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/27d90e2f7db3ff668340823f71d6634728e1a4ac/jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L192-L216), so I've modified the workaround to:

```build.gradle
// build.gradle
asciidoctor {
    jvm {
        jvmArgs(
            "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", 
            "--add-opens", "java.base/java.io=ALL-UNNAMED"
        )
    }
    // ...
}
```

Now the `asciidoctorGemsPrepare` task is still issuing this warning, but I've been unable to find a way to silence it, so this issue should be reopened @juergenzimmermann @ysb33r.
