### ISSUE TITLE
The document should be hosted at docs.asciidoctor.org

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-gradle-plugin#609]
The document should be hosted at docs.asciidoctor.org, like the Maven plugin https://docs.asciidoctor.org/maven-tools/latest/ .

**Comment by abelsromero** [comment]
Glad you noticed, this is something we are already working https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/601, but other things got in-between. I hope to be abel to go back to it soon.
