### ISSUE TITLE
The source files should be annotated with `@IgnoreEmptyDirectories`

### ISSUE THREAD

**Issue by wolfs** [asciidoctor/asciidoctor-gradle-plugin#629]
Gradle 6.8 introduced the annotation `@IgnoreEmptyDirectories`, which allows specifying that an input file property only cares about the files and not about directories. Since both `AbstractAsciidoctorBaseTask.sourceFileTrees` and `AbstractExportBaseTask.slides` are both source files and both tasks don't seem to take directories into account, both should be annotated with `@IgnoreEmptyDirectories`.

The whole plugin would need to be compiled agains Gradle 6.8 at least to add the annotation. Though if nothing else changes, then the tasks would still work with older versions of Gradle, since the annotation would simply be ignored.

**Comment by ysb33r** [comment]
Fixed in 4.0.0-alpha.1
