### ISSUE TITLE
The property "srcDir" in AbstractAsciidoctorBaseTask should be annotated as input property

### ISSUE THREAD

**Issue by bmuschko** [asciidoctor/asciidoctor-gradle-plugin#654]
Right now the property `srcDir` is marked with `@Internal` and therefore changes to the files in the source directory are not picked up properly.

https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy#L116

What was the thought process of marking this as a property to be ignored?

**Comment by ysb33r** [comment]
Not all files in the directory will contribute to the eventual documentation being published. The input files are calculated from the `getSourceFIile()` method which is annotated with `@InputFiles`.

**Comment by bmuschko** [comment]
Thanks for the explanation. I am going to close the issue.

**Comment by FrogDevelopper** [comment]
@ysb33r 
Current [AbstractAsciidoctorBaseTask](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/release_4_0_4/base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy#L235) in version 4.0.4 doesn't have the `@InputFiles`
Is it Intentional ?
