### ISSUE TITLE
Custom AsciidoctorTask task needs sourceDir

### ISSUE THREAD

**Issue by chkpnt** [asciidoctor/asciidoctor-gradle-plugin#688]
When using

```gradle
asciidoctor {
    // ...
}
```

I do not need to specify `sourceDir`, as the default `src/docs/asciidoc` is used.

But if I register my own `AsciidoctorTask`, `sourceDir` needs to be specified explicitly, otherwise the Gradle task is executed with "NO SOURCES":

```gradle
tasks.register("Installation", AsciidoctorTask) {
    group "documentation"
    sourceDir "src/docs/asciidoc"
    sources {
        include "Installation.adoc"
    }
    baseDirFollowsSourceDir()
    outputDir "build/docs/asciidoc/Installation"
}
```

Why is this the case and more important, am I missing other (important) default settings, too, when using a custom `AsciidoctorTask`?

**Comment by ysb33r** [comment]
It is because the `asciidoctor` task is applied by convention. As we do not know the use cases for additional AsciidoctorTask tasks, we cannot set values for those tasks by convention. This is similar to someone creating additional `Jar` tasks in a buidl.
