### ISSUE TITLE
Configuration for PDF output

### ISSUE THREAD

**Issue by glaforge** [asciidoctor/asciidoctor-gradle-plugin#8]
AsciiDoctor's distribution features a command-line tool for generating a PDF output directly:
http://themes.asciidoctor.org/preview/#converting-the-document-to-pdf

It'd be nice if the Gradle plugin would allow configuring PDF output too.

**Comment by robfletcher** [comment]
I've tried doing as suggested above by @aalmiray but I still get `Passing through unknown backend: pdf` when I try to build my book.

**Comment by aalmiray** [comment]
Please ignore that warning. It will be removed in the next release. PDF as output works fine.

**Comment by robfletcher** [comment]
Ah yes. Hadn't noticed the PDF was actually there. D'oh!
