### ISSUE TITLE
Introduce DSL for writing Asciidoctor extensions inline

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-gradle-plugin#95]
Asciidoctor (and AsciidoctorJ) now offers an extension API that accepts extensions as instance objects (and closures). That means, in theory, we should be able to write an extension inside of the `asciidoctor` block in the Gradle build.

It may be necessary to introduce a DSL that accommodates these closures. We may start out with a DSL inside the Maven Gradle plugin and move any shared code upstream into AsciidoctorJ where necessary.

Here's an example of a inline Ruby extension for inspiration.

```
require 'asciidoctor'
require 'asciidoctor/extensions'

include Asciidoctor

Extensions.register {
  preprocessor {
    process {|document, reader|
      Reader.new reader.readlines.map {|l|
        (l.empty? || (l.start_with? '=')) ? l : %(#{l} +)
      }
    }
  }
}
```

See https://github.com/asciidoctor/asciidoctor-extensions-lab/tree/master/lib for more examples.

This should be possible to write in a Gradle build. If it's not, we'll make whatever changes necessary in Asciidoctor core or AsciidoctorJ to accommodate this scenario.

**Comment by msgilligan** [comment]
On Aug 17, 2014, @mojavelinux said:

> In fact, it may make sense to allow the Gradle plugin to activate and configure Asciidoclet to simplify setup

I just created Issue #244 to make the same suggestion.
